// Code generated by Project Forge, see https://projectforge.dev for details.
package database

type SQLiteParams struct {
	File   string `json:"file"`
	Schema string `json:"schema,omitempty"`
	Debug  bool   `json:"debug,omitempty"`
}
