// Code generated by Project Forge, see https://projectforge.dev for details.
import SwiftUI
import AdminiServer

@main
struct Project: App {
    init() {
        print("starting Admini...")
        let path = NSSearchPathForDirectoriesInDomains(.libraryDirectory, .userDomainMask, true)
        let port = AdminiServer.CmdLib(path[0])
        print("Admini started on port [\(port)]")
        let url = URL.init(string: "http://localhost:\(port)/")!
        self.cv = ContentView(url: URLRequest(url: url))
    }

    var cv: ContentView

    var body: some Scene {
        WindowGroup {
            cv
        }
    }
}
