site_name: Admini
site_url: https://admini.dev/
site_description: Explore and manage your data as fast and easily as possible
copyright: Built by @kyleu
repo_name: kyleu/admini
repo_url: https://github.com/kyleu/admini
edit_uri: edit/master/docs
