// Code generated by qtc from "ActionEdit.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/vproject/ActionEdit.html:1
package vproject

//line views/vproject/ActionEdit.html:1
import (
	"github.com/kyleu/admini/app"
	"github.com/kyleu/admini/app/action"
	"github.com/kyleu/admini/app/controller/cutil"
	"github.com/kyleu/admini/app/project"
	"github.com/kyleu/admini/views/components"
	"github.com/kyleu/admini/views/components/fieldview"
	"github.com/kyleu/admini/views/layout"
)

//line views/vproject/ActionEdit.html:11
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/vproject/ActionEdit.html:11
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/vproject/ActionEdit.html:11
type ActionEdit struct {
	layout.Basic
	Project *project.Project
	Act     *action.Action
}

//line views/vproject/ActionEdit.html:17
func (p *ActionEdit) StreamBody(qw422016 *qt422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vproject/ActionEdit.html:17
	qw422016.N().S(`
  <div class="card">
    <div class="right"><em>`)
//line views/vproject/ActionEdit.html:19
	qw422016.E().S(p.Act.Type.Title)
//line views/vproject/ActionEdit.html:19
	qw422016.N().S(`</em></div>
    <h3>`)
//line views/vproject/ActionEdit.html:20
	components.StreamSVGRef(qw422016, p.Act.IconWithFallback(), 20, 20, "icon", ps)
//line views/vproject/ActionEdit.html:20
	qw422016.E().S(p.Act.Name())
//line views/vproject/ActionEdit.html:20
	qw422016.N().S(`</h3>
    <em>`)
//line views/vproject/ActionEdit.html:21
	qw422016.E().S(p.Act.ConfigString())
//line views/vproject/ActionEdit.html:21
	qw422016.N().S(`</em>
    <form class="mt" action="/project/`)
//line views/vproject/ActionEdit.html:22
	qw422016.E().S(p.Project.Key)
//line views/vproject/ActionEdit.html:22
	qw422016.N().S(`/action/`)
//line views/vproject/ActionEdit.html:22
	qw422016.E().S(p.Act.Pkg.ToPath(p.Act.Key))
//line views/vproject/ActionEdit.html:22
	qw422016.N().S(`" method="post" enctype="application/x-www-form-urlencoded">
      <table>
        <tbody>
          `)
//line views/vproject/ActionEdit.html:25
	components.StreamTableInput(qw422016, "key", "Key", p.Act.Key, 5)
//line views/vproject/ActionEdit.html:25
	qw422016.N().S(`
`)
//line views/vproject/ActionEdit.html:26
	if p.Act.Type != action.TypeSeparator {
//line views/vproject/ActionEdit.html:26
		qw422016.N().S(`          `)
//line views/vproject/ActionEdit.html:27
		components.StreamTableInput(qw422016, "title", "Title", p.Act.Title, 5)
//line views/vproject/ActionEdit.html:27
		qw422016.N().S(`
          `)
//line views/vproject/ActionEdit.html:28
		components.StreamTableIcons(qw422016, "icon", "Icon", p.Act.Icon, ps, 5)
//line views/vproject/ActionEdit.html:28
		qw422016.N().S(`
          `)
//line views/vproject/ActionEdit.html:29
		components.StreamTableTextarea(qw422016, "description", "Description", 8, p.Act.Description, 5)
//line views/vproject/ActionEdit.html:29
		qw422016.N().S(`
`)
//line views/vproject/ActionEdit.html:30
	}
//line views/vproject/ActionEdit.html:31
	switch p.Act.Type {
//line views/vproject/ActionEdit.html:32
	case action.TypeStatic:
//line views/vproject/ActionEdit.html:34
		format, _ := p.Act.Config["format"].(string)
		content, _ := p.Act.Config["content"].(string)

//line views/vproject/ActionEdit.html:36
		qw422016.N().S(`          `)
//line views/vproject/ActionEdit.html:37
		components.StreamTableSelect(qw422016, "format", "Format", format, []string{"html", "text", "code"}, []string{"HTML", "Text", "Code"}, 5)
//line views/vproject/ActionEdit.html:37
		qw422016.N().S(`
          `)
//line views/vproject/ActionEdit.html:38
		components.StreamTableTextarea(qw422016, "content", "Content", 8, content, 5)
//line views/vproject/ActionEdit.html:38
		qw422016.N().S(`
`)
//line views/vproject/ActionEdit.html:39
	}
//line views/vproject/ActionEdit.html:39
	qw422016.N().S(`        </tbody>
      </table>
      <div class="mt">
        <button type="submit">Save Changes</button>
        <a href="/project/`)
//line views/vproject/ActionEdit.html:44
	qw422016.E().S(p.Project.Key)
//line views/vproject/ActionEdit.html:44
	qw422016.N().S(`"><button type="button">Cancel</button></a>
      </div>
    </form>
  </div>
  <div class="card">
    <h3>Action JSON</h3>
    `)
//line views/vproject/ActionEdit.html:50
	fieldview.StreamJSON(qw422016, p.Act)
//line views/vproject/ActionEdit.html:50
	qw422016.N().S(`
  </div>
`)
//line views/vproject/ActionEdit.html:52
}

//line views/vproject/ActionEdit.html:52
func (p *ActionEdit) WriteBody(qq422016 qtio422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vproject/ActionEdit.html:52
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vproject/ActionEdit.html:52
	p.StreamBody(qw422016, as, ps)
//line views/vproject/ActionEdit.html:52
	qt422016.ReleaseWriter(qw422016)
//line views/vproject/ActionEdit.html:52
}

//line views/vproject/ActionEdit.html:52
func (p *ActionEdit) Body(as *app.State, ps *cutil.PageState) string {
//line views/vproject/ActionEdit.html:52
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vproject/ActionEdit.html:52
	p.WriteBody(qb422016, as, ps)
//line views/vproject/ActionEdit.html:52
	qs422016 := string(qb422016.B)
//line views/vproject/ActionEdit.html:52
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vproject/ActionEdit.html:52
	return qs422016
//line views/vproject/ActionEdit.html:52
}
