// Code generated by qtc from "ActionAvailable.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/vproject/ActionAvailable.html:1
package vproject

//line views/vproject/ActionAvailable.html:1
import (
	"admini.dev/app"
	"admini.dev/app/action"
	"admini.dev/app/controller/cutil"
	"admini.dev/app/lib/schema"
	"admini.dev/app/lib/schema/model"
	"admini.dev/app/project"
	"admini.dev/app/source"
	"admini.dev/views/vutil"
	"fmt"
)

//line views/vproject/ActionAvailable.html:13
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/vproject/ActionAvailable.html:13
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/vproject/ActionAvailable.html:13
func StreamActionAvailable(qw422016 *qt422016.Writer, v *project.View, as *app.State, ps *cutil.PageState, indent int) {
//line views/vproject/ActionAvailable.html:13
	qw422016.N().S(`<div class="container">`)
//line views/vproject/ActionAvailable.html:15
	streamitemTemplate(qw422016, action.TypeFolder, `folder`, `New Folder`, indent)
//line views/vproject/ActionAvailable.html:16
	streamitemTemplate(qw422016, action.TypeStatic, action.TypeStatic.Key, `Static Content`, indent)
//line views/vproject/ActionAvailable.html:17
	streamitemTemplate(qw422016, action.TypeSeparator, action.TypeSeparator.Key, `Separator`, indent)
//line views/vproject/ActionAvailable.html:18
	streamitemTemplate(qw422016, action.TypeAll, action.TypeAll.Key, `All Sources`, indent)
//line views/vproject/ActionAvailable.html:19
	for _, src := range v.Sources {
//line views/vproject/ActionAvailable.html:20
		streamitemSchema(qw422016, src, v.Schemata.Get(src.Key), indent)
//line views/vproject/ActionAvailable.html:21
	}
//line views/vproject/ActionAvailable.html:21
	qw422016.N().S(`</div>`)
//line views/vproject/ActionAvailable.html:23
}

//line views/vproject/ActionAvailable.html:23
func WriteActionAvailable(qq422016 qtio422016.Writer, v *project.View, as *app.State, ps *cutil.PageState, indent int) {
//line views/vproject/ActionAvailable.html:23
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vproject/ActionAvailable.html:23
	StreamActionAvailable(qw422016, v, as, ps, indent)
//line views/vproject/ActionAvailable.html:23
	qt422016.ReleaseWriter(qw422016)
//line views/vproject/ActionAvailable.html:23
}

//line views/vproject/ActionAvailable.html:23
func ActionAvailable(v *project.View, as *app.State, ps *cutil.PageState, indent int) string {
//line views/vproject/ActionAvailable.html:23
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vproject/ActionAvailable.html:23
	WriteActionAvailable(qb422016, v, as, ps, indent)
//line views/vproject/ActionAvailable.html:23
	qs422016 := string(qb422016.B)
//line views/vproject/ActionAvailable.html:23
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vproject/ActionAvailable.html:23
	return qs422016
//line views/vproject/ActionAvailable.html:23
}

//line views/vproject/ActionAvailable.html:25
func streamitemSchema(qw422016 *qt422016.Writer, src *source.Source, sch *schema.Schema, indent int) {
//line views/vproject/ActionAvailable.html:26
	streamitemTemplate(qw422016, action.TypeSource, `source/`+src.Key, src.Name(), 5)
//line views/vproject/ActionAvailable.html:27
	streamitemTemplate(qw422016, action.TypeActivity, `activity/`+src.Key+"/sql", "SQL Playground", 5)
//line views/vproject/ActionAvailable.html:28
	streamitemModelPackage(qw422016, src, sch.ModelsByPackage(), false, 5)
//line views/vproject/ActionAvailable.html:29
}

//line views/vproject/ActionAvailable.html:29
func writeitemSchema(qq422016 qtio422016.Writer, src *source.Source, sch *schema.Schema, indent int) {
//line views/vproject/ActionAvailable.html:29
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vproject/ActionAvailable.html:29
	streamitemSchema(qw422016, src, sch, indent)
//line views/vproject/ActionAvailable.html:29
	qt422016.ReleaseWriter(qw422016)
//line views/vproject/ActionAvailable.html:29
}

//line views/vproject/ActionAvailable.html:29
func itemSchema(src *source.Source, sch *schema.Schema, indent int) string {
//line views/vproject/ActionAvailable.html:29
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vproject/ActionAvailable.html:29
	writeitemSchema(qb422016, src, sch, indent)
//line views/vproject/ActionAvailable.html:29
	qs422016 := string(qb422016.B)
//line views/vproject/ActionAvailable.html:29
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vproject/ActionAvailable.html:29
	return qs422016
//line views/vproject/ActionAvailable.html:29
}

//line views/vproject/ActionAvailable.html:31
func streamitemModelPackage(qw422016 *qt422016.Writer, src *source.Source, pkg *model.Package, showRoot bool, indent int) {
//line views/vproject/ActionAvailable.html:32
	if showRoot {
//line views/vproject/ActionAvailable.html:33
		streamitemTemplate(qw422016, action.TypePackage, fmt.Sprintf("package/%s/%s", src.Key, pkg.PathString()), pkg.Key, indent)
//line views/vproject/ActionAvailable.html:34
	}
//line views/vproject/ActionAvailable.html:35
	for _, p := range pkg.ChildPackages {
//line views/vproject/ActionAvailable.html:36
		vutil.StreamIndent(qw422016, true, indent)
//line views/vproject/ActionAvailable.html:37
		streamitemModelPackage(qw422016, src, p, true, indent)
//line views/vproject/ActionAvailable.html:38
	}
//line views/vproject/ActionAvailable.html:39
	for _, m := range pkg.ChildModels {
//line views/vproject/ActionAvailable.html:40
		vutil.StreamIndent(qw422016, true, indent)
//line views/vproject/ActionAvailable.html:41
		streamitemTemplate(qw422016, action.TypeModel, fmt.Sprintf("model/%s/%s", src.Key, m.PathString()), m.Name(), indent)
//line views/vproject/ActionAvailable.html:42
	}
//line views/vproject/ActionAvailable.html:43
}

//line views/vproject/ActionAvailable.html:43
func writeitemModelPackage(qq422016 qtio422016.Writer, src *source.Source, pkg *model.Package, showRoot bool, indent int) {
//line views/vproject/ActionAvailable.html:43
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vproject/ActionAvailable.html:43
	streamitemModelPackage(qw422016, src, pkg, showRoot, indent)
//line views/vproject/ActionAvailable.html:43
	qt422016.ReleaseWriter(qw422016)
//line views/vproject/ActionAvailable.html:43
}

//line views/vproject/ActionAvailable.html:43
func itemModelPackage(src *source.Source, pkg *model.Package, showRoot bool, indent int) string {
//line views/vproject/ActionAvailable.html:43
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vproject/ActionAvailable.html:43
	writeitemModelPackage(qb422016, src, pkg, showRoot, indent)
//line views/vproject/ActionAvailable.html:43
	qs422016 := string(qb422016.B)
//line views/vproject/ActionAvailable.html:43
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vproject/ActionAvailable.html:43
	return qs422016
//line views/vproject/ActionAvailable.html:43
}

//line views/vproject/ActionAvailable.html:45
func streamitemTemplate(qw422016 *qt422016.Writer, t *action.Type, path string, title string, indent int) {
//line views/vproject/ActionAvailable.html:45
	qw422016.N().S(`<div class="item`)
//line views/vproject/ActionAvailable.html:46
	qw422016.N().S(` `)
//line views/vproject/ActionAvailable.html:46
	qw422016.E().S(t.Key)
//line views/vproject/ActionAvailable.html:46
	qw422016.N().S(`" data-key="_new" data-title="`)
//line views/vproject/ActionAvailable.html:46
	qw422016.E().S(title)
//line views/vproject/ActionAvailable.html:46
	qw422016.N().S(`" data-original-path="`)
//line views/vproject/ActionAvailable.html:46
	qw422016.E().S(path)
//line views/vproject/ActionAvailable.html:46
	qw422016.N().S(`">`)
//line views/vproject/ActionAvailable.html:47
	vutil.StreamIndent(qw422016, true, indent+1)
//line views/vproject/ActionAvailable.html:47
	qw422016.N().S(`<div class="content">`)
//line views/vproject/ActionAvailable.html:49
	vutil.StreamIndent(qw422016, true, indent+2)
//line views/vproject/ActionAvailable.html:49
	qw422016.N().S(`<div class="handle">≡</div>`)
//line views/vproject/ActionAvailable.html:51
	vutil.StreamIndent(qw422016, true, indent+2)
//line views/vproject/ActionAvailable.html:51
	qw422016.N().S(`<div class="title">`)
//line views/vproject/ActionAvailable.html:52
	qw422016.E().S(title)
//line views/vproject/ActionAvailable.html:52
	qw422016.N().S(`</div>`)
//line views/vproject/ActionAvailable.html:53
	vutil.StreamIndent(qw422016, true, indent+2)
//line views/vproject/ActionAvailable.html:53
	qw422016.N().S(`<div class="remove">×</div>`)
//line views/vproject/ActionAvailable.html:55
	vutil.StreamIndent(qw422016, true, indent+1)
//line views/vproject/ActionAvailable.html:55
	qw422016.N().S(`</div>`)
//line views/vproject/ActionAvailable.html:57
	vutil.StreamIndent(qw422016, true, indent+1)
//line views/vproject/ActionAvailable.html:57
	qw422016.N().S(`<div class="container"></div>`)
//line views/vproject/ActionAvailable.html:59
	vutil.StreamIndent(qw422016, true, indent)
//line views/vproject/ActionAvailable.html:59
	qw422016.N().S(`</div>`)
//line views/vproject/ActionAvailable.html:61
}

//line views/vproject/ActionAvailable.html:61
func writeitemTemplate(qq422016 qtio422016.Writer, t *action.Type, path string, title string, indent int) {
//line views/vproject/ActionAvailable.html:61
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vproject/ActionAvailable.html:61
	streamitemTemplate(qw422016, t, path, title, indent)
//line views/vproject/ActionAvailable.html:61
	qt422016.ReleaseWriter(qw422016)
//line views/vproject/ActionAvailable.html:61
}

//line views/vproject/ActionAvailable.html:61
func itemTemplate(t *action.Type, path string, title string, indent int) string {
//line views/vproject/ActionAvailable.html:61
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vproject/ActionAvailable.html:61
	writeitemTemplate(qb422016, t, path, title, indent)
//line views/vproject/ActionAvailable.html:61
	qs422016 := string(qb422016.B)
//line views/vproject/ActionAvailable.html:61
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vproject/ActionAvailable.html:61
	return qs422016
//line views/vproject/ActionAvailable.html:61
}
