// Code generated by qtc from "ActionList.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/vproject/ActionList.html:1
package vproject

//line views/vproject/ActionList.html:1
import (
	"github.com/kyleu/admini/app"
	"github.com/kyleu/admini/app/action"
	"github.com/kyleu/admini/app/controller/cutil"
	"github.com/kyleu/admini/views/components"
	"github.com/kyleu/admini/views/vutil"
)

//line views/vproject/ActionList.html:9
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/vproject/ActionList.html:9
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/vproject/ActionList.html:9
func StreamActionList(qw422016 *qt422016.Writer, prj string, act *action.Action, as *app.State, ps *cutil.PageState, indent int) {
//line views/vproject/ActionList.html:9
	qw422016.N().S(`<div class="item" data-key="`)
//line views/vproject/ActionList.html:10
	qw422016.E().S(act.Key)
//line views/vproject/ActionList.html:10
	qw422016.N().S(`" data-title="`)
//line views/vproject/ActionList.html:10
	qw422016.E().S(act.Title)
//line views/vproject/ActionList.html:10
	qw422016.N().S(`" data-original-path="`)
//line views/vproject/ActionList.html:10
	qw422016.E().S(act.Pkg.ToPath(act.Key))
//line views/vproject/ActionList.html:10
	qw422016.N().S(`">`)
//line views/vproject/ActionList.html:11
	vutil.StreamIndent(qw422016, true, indent+1)
//line views/vproject/ActionList.html:11
	qw422016.N().S(`<div class="content">`)
//line views/vproject/ActionList.html:13
	vutil.StreamIndent(qw422016, true, indent+2)
//line views/vproject/ActionList.html:13
	qw422016.N().S(`<div class="handle">≡</div>`)
//line views/vproject/ActionList.html:15
	vutil.StreamIndent(qw422016, true, indent+2)
//line views/vproject/ActionList.html:15
	qw422016.N().S(`<div class="title">`)
//line views/vproject/ActionList.html:17
	if act.Type().Key == action.TypeSeparator.Key {
//line views/vproject/ActionList.html:17
		qw422016.N().S(`<em>Separator</em>`)
//line views/vproject/ActionList.html:19
	} else {
//line views/vproject/ActionList.html:19
		qw422016.N().S(`<a href="/project/`)
//line views/vproject/ActionList.html:20
		qw422016.E().S(prj)
//line views/vproject/ActionList.html:20
		qw422016.N().S(`/action/`)
//line views/vproject/ActionList.html:20
		qw422016.E().S(act.Pkg.ToPath(act.Key))
//line views/vproject/ActionList.html:20
		qw422016.N().S(`">`)
//line views/vproject/ActionList.html:21
		components.StreamSVGRef(qw422016, act.IconWithFallback(), 16, 16, "icon", ps)
//line views/vproject/ActionList.html:22
		qw422016.E().S(act.Name())
//line views/vproject/ActionList.html:22
		qw422016.N().S(`</a>`)
//line views/vproject/ActionList.html:24
	}
//line views/vproject/ActionList.html:24
	qw422016.N().S(`</div>`)
//line views/vproject/ActionList.html:26
	vutil.StreamIndent(qw422016, true, indent+2)
//line views/vproject/ActionList.html:26
	qw422016.N().S(`<div class="remove">×</div>`)
//line views/vproject/ActionList.html:28
	vutil.StreamIndent(qw422016, true, indent+1)
//line views/vproject/ActionList.html:28
	qw422016.N().S(`</div>`)
//line views/vproject/ActionList.html:30
	vutil.StreamIndent(qw422016, true, indent+1)
//line views/vproject/ActionList.html:31
	if len(act.Children) == 0 {
//line views/vproject/ActionList.html:31
		qw422016.N().S(`<div class="container"></div>`)
//line views/vproject/ActionList.html:33
	} else {
//line views/vproject/ActionList.html:33
		qw422016.N().S(`<div class="container">`)
//line views/vproject/ActionList.html:35
		for _, kid := range act.Children {
//line views/vproject/ActionList.html:36
			vutil.StreamIndent(qw422016, true, indent+2)
//line views/vproject/ActionList.html:37
			StreamActionList(qw422016, prj, kid, as, ps, indent+2)
//line views/vproject/ActionList.html:38
		}
//line views/vproject/ActionList.html:39
		vutil.StreamIndent(qw422016, true, indent+1)
//line views/vproject/ActionList.html:39
		qw422016.N().S(`</div>`)
//line views/vproject/ActionList.html:41
	}
//line views/vproject/ActionList.html:42
	vutil.StreamIndent(qw422016, true, indent)
//line views/vproject/ActionList.html:42
	qw422016.N().S(`</div>`)
//line views/vproject/ActionList.html:44
}

//line views/vproject/ActionList.html:44
func WriteActionList(qq422016 qtio422016.Writer, prj string, act *action.Action, as *app.State, ps *cutil.PageState, indent int) {
//line views/vproject/ActionList.html:44
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vproject/ActionList.html:44
	StreamActionList(qw422016, prj, act, as, ps, indent)
//line views/vproject/ActionList.html:44
	qt422016.ReleaseWriter(qw422016)
//line views/vproject/ActionList.html:44
}

//line views/vproject/ActionList.html:44
func ActionList(prj string, act *action.Action, as *app.State, ps *cutil.PageState, indent int) string {
//line views/vproject/ActionList.html:44
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vproject/ActionList.html:44
	WriteActionList(qb422016, prj, act, as, ps, indent)
//line views/vproject/ActionList.html:44
	qs422016 := string(qb422016.B)
//line views/vproject/ActionList.html:44
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vproject/ActionList.html:44
	return qs422016
//line views/vproject/ActionList.html:44
}
