// Code generated by qtc from "ActionList.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/vproject/ActionList.html:1
package vproject

//line views/vproject/ActionList.html:1
import (
	"github.com/kyleu/admini/app"
	"github.com/kyleu/admini/app/action"
	"github.com/kyleu/admini/app/controller/cutil"
	"github.com/kyleu/admini/views/components"
	"github.com/kyleu/admini/views/vutil"
)

//line views/vproject/ActionList.html:9
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/vproject/ActionList.html:9
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/vproject/ActionList.html:9
func StreamActionList(qw422016 *qt422016.Writer, prj string, act *action.Action, as *app.State, ps *cutil.PageState, indent int) {
//line views/vproject/ActionList.html:9
	qw422016.N().S(`<div class="item" data-key="`)
//line views/vproject/ActionList.html:10
	qw422016.E().S(act.Key)
//line views/vproject/ActionList.html:10
	qw422016.N().S(`" data-original-path="`)
//line views/vproject/ActionList.html:10
	qw422016.E().S(act.Pkg.ToPath(act.Key))
//line views/vproject/ActionList.html:10
	qw422016.N().S(`">`)
//line views/vproject/ActionList.html:11
	vutil.StreamIndent(qw422016, true, indent+1)
//line views/vproject/ActionList.html:11
	qw422016.N().S(`<div class="content">`)
//line views/vproject/ActionList.html:13
	vutil.StreamIndent(qw422016, true, indent+2)
//line views/vproject/ActionList.html:13
	qw422016.N().S(`<div class="handle">≡</div>`)
//line views/vproject/ActionList.html:15
	vutil.StreamIndent(qw422016, true, indent+2)
//line views/vproject/ActionList.html:15
	qw422016.N().S(`<div class="title"><a href="/project/`)
//line views/vproject/ActionList.html:17
	qw422016.E().S(prj)
//line views/vproject/ActionList.html:17
	qw422016.N().S(`/action/`)
//line views/vproject/ActionList.html:17
	qw422016.E().S(act.Pkg.ToPath(act.Key))
//line views/vproject/ActionList.html:17
	qw422016.N().S(`">`)
//line views/vproject/ActionList.html:18
	components.StreamSVGRef(qw422016, act.IconWithFallback(), 16, 16, "icon", ps)
//line views/vproject/ActionList.html:19
	qw422016.E().S(act.Name())
//line views/vproject/ActionList.html:19
	qw422016.N().S(`</a></div>`)
//line views/vproject/ActionList.html:22
	vutil.StreamIndent(qw422016, true, indent+2)
//line views/vproject/ActionList.html:22
	qw422016.N().S(`<div class="remove">×</div>`)
//line views/vproject/ActionList.html:24
	vutil.StreamIndent(qw422016, true, indent+1)
//line views/vproject/ActionList.html:24
	qw422016.N().S(`</div>`)
//line views/vproject/ActionList.html:26
	vutil.StreamIndent(qw422016, true, indent+1)
//line views/vproject/ActionList.html:27
	if len(act.Children) == 0 {
//line views/vproject/ActionList.html:27
		qw422016.N().S(`<div class="container"></div>`)
//line views/vproject/ActionList.html:29
	} else {
//line views/vproject/ActionList.html:29
		qw422016.N().S(`<div class="container">`)
//line views/vproject/ActionList.html:31
		for _, kid := range act.Children {
//line views/vproject/ActionList.html:32
			vutil.StreamIndent(qw422016, true, indent+2)
//line views/vproject/ActionList.html:33
			StreamActionList(qw422016, prj, kid, as, ps, indent+2)
//line views/vproject/ActionList.html:34
		}
//line views/vproject/ActionList.html:35
		vutil.StreamIndent(qw422016, true, indent+1)
//line views/vproject/ActionList.html:35
		qw422016.N().S(`</div>`)
//line views/vproject/ActionList.html:37
	}
//line views/vproject/ActionList.html:38
	vutil.StreamIndent(qw422016, true, indent)
//line views/vproject/ActionList.html:38
	qw422016.N().S(`</div>`)
//line views/vproject/ActionList.html:40
}

//line views/vproject/ActionList.html:40
func WriteActionList(qq422016 qtio422016.Writer, prj string, act *action.Action, as *app.State, ps *cutil.PageState, indent int) {
//line views/vproject/ActionList.html:40
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vproject/ActionList.html:40
	StreamActionList(qw422016, prj, act, as, ps, indent)
//line views/vproject/ActionList.html:40
	qt422016.ReleaseWriter(qw422016)
//line views/vproject/ActionList.html:40
}

//line views/vproject/ActionList.html:40
func ActionList(prj string, act *action.Action, as *app.State, ps *cutil.PageState, indent int) string {
//line views/vproject/ActionList.html:40
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vproject/ActionList.html:40
	WriteActionList(qb422016, prj, act, as, ps, indent)
//line views/vproject/ActionList.html:40
	qs422016 := string(qb422016.B)
//line views/vproject/ActionList.html:40
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vproject/ActionList.html:40
	return qs422016
//line views/vproject/ActionList.html:40
}
