// Code generated by qtc from "Table.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/vproject/Table.html:1
package vproject

//line views/vproject/Table.html:1
import (
	"admini.dev/admini/app"
	"admini.dev/admini/app/controller/cutil"
	"admini.dev/admini/app/project"
	"admini.dev/admini/views/components"
)

//line views/vproject/Table.html:8
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/vproject/Table.html:8
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/vproject/Table.html:8
func StreamTable(qw422016 *qt422016.Writer, projects project.Projects, as *app.State, ps *cutil.PageState) {
//line views/vproject/Table.html:8
	qw422016.N().S(`    <table>
      <thead>
        <tr>
          <th style="width: 30%;">Name</th>
          <th>Description</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
`)
//line views/vproject/Table.html:18
	for _, p := range projects {
//line views/vproject/Table.html:18
		qw422016.N().S(`        <tr>
          <td><a href="/project/`)
//line views/vproject/Table.html:20
		qw422016.E().S(p.Key)
//line views/vproject/Table.html:20
		qw422016.N().S(`">`)
//line views/vproject/Table.html:20
		components.StreamSVGRef(qw422016, p.IconWithFallback(), 16, 16, "icon", ps)
//line views/vproject/Table.html:20
		qw422016.E().S(p.Name())
//line views/vproject/Table.html:20
		qw422016.N().S(`</a></td>
          <td>`)
//line views/vproject/Table.html:21
		qw422016.E().S(p.Description)
//line views/vproject/Table.html:21
		qw422016.N().S(`</td>
          <td class="shrink">
            <a href="/x/`)
//line views/vproject/Table.html:23
		qw422016.E().S(p.Key)
//line views/vproject/Table.html:23
		qw422016.N().S(`"><button type="button">workspace</button></a>
          </td>
        </tr>
`)
//line views/vproject/Table.html:26
	}
//line views/vproject/Table.html:26
	qw422016.N().S(`      </tbody>
    </table>
`)
//line views/vproject/Table.html:29
}

//line views/vproject/Table.html:29
func WriteTable(qq422016 qtio422016.Writer, projects project.Projects, as *app.State, ps *cutil.PageState) {
//line views/vproject/Table.html:29
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vproject/Table.html:29
	StreamTable(qw422016, projects, as, ps)
//line views/vproject/Table.html:29
	qt422016.ReleaseWriter(qw422016)
//line views/vproject/Table.html:29
}

//line views/vproject/Table.html:29
func Table(projects project.Projects, as *app.State, ps *cutil.PageState) string {
//line views/vproject/Table.html:29
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vproject/Table.html:29
	WriteTable(qb422016, projects, as, ps)
//line views/vproject/Table.html:29
	qs422016 := string(qb422016.B)
//line views/vproject/Table.html:29
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vproject/Table.html:29
	return qs422016
//line views/vproject/Table.html:29
}
