// Code generated by qtc from "Test.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/vproject/Test.html:1
package vproject

//line views/vproject/Test.html:1
import (
	"admini.dev/admini/app"
	"admini.dev/admini/app/controller/cutil"
	"admini.dev/admini/views/components"
	"admini.dev/admini/views/layout"
)

//line views/vproject/Test.html:8
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/vproject/Test.html:8
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/vproject/Test.html:8
type Test struct {
	layout.Basic
	Message string
}

//line views/vproject/Test.html:13
func (p *Test) StreamBody(qw422016 *qt422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vproject/Test.html:13
	qw422016.N().S(`
  <div class="card">
    <h3>Project Test</h3>
    <p>`)
//line views/vproject/Test.html:16
	qw422016.E().S(p.Message)
//line views/vproject/Test.html:16
	qw422016.N().S(`</p>
    `)
//line views/vproject/Test.html:17
	if ps.Data != nil {
//line views/vproject/Test.html:17
		components.StreamJSON(qw422016, ps.Data)
//line views/vproject/Test.html:17
	}
//line views/vproject/Test.html:17
	qw422016.N().S(`
  </div>
`)
//line views/vproject/Test.html:19
}

//line views/vproject/Test.html:19
func (p *Test) WriteBody(qq422016 qtio422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vproject/Test.html:19
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vproject/Test.html:19
	p.StreamBody(qw422016, as, ps)
//line views/vproject/Test.html:19
	qt422016.ReleaseWriter(qw422016)
//line views/vproject/Test.html:19
}

//line views/vproject/Test.html:19
func (p *Test) Body(as *app.State, ps *cutil.PageState) string {
//line views/vproject/Test.html:19
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vproject/Test.html:19
	p.WriteBody(qb422016, as, ps)
//line views/vproject/Test.html:19
	qs422016 := string(qb422016.B)
//line views/vproject/Test.html:19
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vproject/Test.html:19
	return qs422016
//line views/vproject/Test.html:19
}
