// Code generated by qtc from "Home.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/Home.html:1
package views

//line views/Home.html:1
import (
	"admini.dev/admini/app"
	"admini.dev/admini/app/controller/cutil"
	"admini.dev/admini/app/lib/sandbox"
	"admini.dev/admini/app/project"
	"admini.dev/admini/app/source"
	"admini.dev/admini/app/util"
	"admini.dev/admini/views/components"
	"admini.dev/admini/views/layout"
	"admini.dev/admini/views/vproject"
	"admini.dev/admini/views/vsource"
)

//line views/Home.html:14
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/Home.html:14
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/Home.html:14
type Home struct {
	layout.Basic
	Sources  source.Sources
	Projects project.Projects
}

//line views/Home.html:20
func (p *Home) StreamBody(qw422016 *qt422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/Home.html:20
	qw422016.N().S(`
  <div class="card">
    <h3>`)
//line views/Home.html:22
	components.StreamSVGRef(qw422016, `app`, 20, 20, `icon`, ps)
//line views/Home.html:22
	qw422016.E().S(util.AppName)
//line views/Home.html:22
	qw422016.N().S(`</h3>
  </div>

  <div class="card">
    <div class="right"><a href="/project/_new" title="add new project">`)
//line views/Home.html:26
	components.StreamSVGRef(qw422016, `plus`, 20, 20, `icon`, ps)
//line views/Home.html:26
	qw422016.N().S(`</a></div>
    <h3><a href="/project">Projects</a></h3>
`)
//line views/Home.html:28
	if len(p.Projects) == 0 {
//line views/Home.html:28
		qw422016.N().S(`    <p>no projects available, why not <a href="/project/_new" title="add new project">add one</a></p>
`)
//line views/Home.html:30
	} else {
//line views/Home.html:31
		vproject.StreamTable(qw422016, p.Projects, as, ps)
//line views/Home.html:32
	}
//line views/Home.html:32
	qw422016.N().S(`  </div>

  <div class="card">
    <div class="right"><a href="/source/_new" title="add new source">`)
//line views/Home.html:36
	components.StreamSVGRef(qw422016, `plus`, 20, 20, `icon`, ps)
//line views/Home.html:36
	qw422016.N().S(`</a></div>
    <h3><a href="/source">Sources</a></h3>
`)
//line views/Home.html:38
	if len(p.Sources) == 0 {
//line views/Home.html:38
		qw422016.N().S(`    <p>No sources configured. Would you like to <a href="/source/_new" title="add new source">add a new source</a> or <a href="/source/_example">load the example database</a>?</p>
`)
//line views/Home.html:40
	} else {
//line views/Home.html:41
		vsource.StreamTable(qw422016, p.Sources, as, ps)
//line views/Home.html:42
	}
//line views/Home.html:42
	qw422016.N().S(`  </div>

  <div class="card">
    <h3><a href="/sandbox">Sandboxes</a></h3>
    <ul>
`)
//line views/Home.html:48
	for _, s := range sandbox.AllSandboxes {
//line views/Home.html:48
		qw422016.N().S(`      <li><a href="/sandbox/`)
//line views/Home.html:49
		qw422016.E().S(s.Key)
//line views/Home.html:49
		qw422016.N().S(`">`)
//line views/Home.html:49
		qw422016.E().S(s.Title)
//line views/Home.html:49
		qw422016.N().S(`</a></li>
`)
//line views/Home.html:50
	}
//line views/Home.html:50
	qw422016.N().S(`    </ul>
  </div>
`)
//line views/Home.html:53
}

//line views/Home.html:53
func (p *Home) WriteBody(qq422016 qtio422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/Home.html:53
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/Home.html:53
	p.StreamBody(qw422016, as, ps)
//line views/Home.html:53
	qt422016.ReleaseWriter(qw422016)
//line views/Home.html:53
}

//line views/Home.html:53
func (p *Home) Body(as *app.State, ps *cutil.PageState) string {
//line views/Home.html:53
	qb422016 := qt422016.AcquireByteBuffer()
//line views/Home.html:53
	p.WriteBody(qb422016, as, ps)
//line views/Home.html:53
	qs422016 := string(qb422016.B)
//line views/Home.html:53
	qt422016.ReleaseByteBuffer(qb422016)
//line views/Home.html:53
	return qs422016
//line views/Home.html:53
}
