// Code generated by qtc from "ExampleDatabase.sql". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// --

//line queries/qsqlserver/ExampleDatabase.sql:1
package qsqlserver

//line queries/qsqlserver/ExampleDatabase.sql:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line queries/qsqlserver/ExampleDatabase.sql:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line queries/qsqlserver/ExampleDatabase.sql:1
func StreamExampleDatabase(qw422016 *qt422016.Writer) {
//line queries/qsqlserver/ExampleDatabase.sql:1
	qw422016.N().S(`
-- `)
//line queries/qsqlserver/ExampleDatabase.sql:2
}

//line queries/qsqlserver/ExampleDatabase.sql:2
func WriteExampleDatabase(qq422016 qtio422016.Writer) {
//line queries/qsqlserver/ExampleDatabase.sql:2
	qw422016 := qt422016.AcquireWriter(qq422016)
//line queries/qsqlserver/ExampleDatabase.sql:2
	StreamExampleDatabase(qw422016)
//line queries/qsqlserver/ExampleDatabase.sql:2
	qt422016.ReleaseWriter(qw422016)
//line queries/qsqlserver/ExampleDatabase.sql:2
}

//line queries/qsqlserver/ExampleDatabase.sql:2
func ExampleDatabase() string {
//line queries/qsqlserver/ExampleDatabase.sql:2
	qb422016 := qt422016.AcquireByteBuffer()
//line queries/qsqlserver/ExampleDatabase.sql:2
	WriteExampleDatabase(qb422016)
//line queries/qsqlserver/ExampleDatabase.sql:2
	qs422016 := string(qb422016.B)
//line queries/qsqlserver/ExampleDatabase.sql:2
	qt422016.ReleaseByteBuffer(qb422016)
//line queries/qsqlserver/ExampleDatabase.sql:2
	return qs422016
//line queries/qsqlserver/ExampleDatabase.sql:2
}
