// Code generated by qtc from "ListForeignKeys.sql". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// --

//line queries/qsqlserver/ListForeignKeys.sql:1
package qsqlserver

//line queries/qsqlserver/ListForeignKeys.sql:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line queries/qsqlserver/ListForeignKeys.sql:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line queries/qsqlserver/ListForeignKeys.sql:1
func StreamListForeignKeys(qw422016 *qt422016.Writer, schema string) {
//line queries/qsqlserver/ListForeignKeys.sql:1
	qw422016.N().S(`
select
  obj.name as fk,
  sch.name as sch,
  tab1.name as tbl,
  col1.name as col,
  tab2.name as ref_tbl,
  col2.name as ref_col
from
  sys.foreign_key_columns fkc
    inner join sys.objects obj on obj.object_id = fkc.constraint_object_id
    inner join sys.tables tab1 on tab1.object_id = fkc.parent_object_id
    inner join sys.schemas sch on tab1.schema_id = sch.schema_id
    inner join sys.columns col1 on col1.column_id = parent_column_id and col1.object_id = tab1.object_id
    inner join sys.tables tab2 on tab2.object_id = fkc.referenced_object_id
    inner join sys.columns col2 on col2.column_id = referenced_column_id and col2.object_id = tab2.object_id
order by
  sch, tbl, col
-- `)
//line queries/qsqlserver/ListForeignKeys.sql:19
}

//line queries/qsqlserver/ListForeignKeys.sql:19
func WriteListForeignKeys(qq422016 qtio422016.Writer, schema string) {
//line queries/qsqlserver/ListForeignKeys.sql:19
	qw422016 := qt422016.AcquireWriter(qq422016)
//line queries/qsqlserver/ListForeignKeys.sql:19
	StreamListForeignKeys(qw422016, schema)
//line queries/qsqlserver/ListForeignKeys.sql:19
	qt422016.ReleaseWriter(qw422016)
//line queries/qsqlserver/ListForeignKeys.sql:19
}

//line queries/qsqlserver/ListForeignKeys.sql:19
func ListForeignKeys(schema string) string {
//line queries/qsqlserver/ListForeignKeys.sql:19
	qb422016 := qt422016.AcquireByteBuffer()
//line queries/qsqlserver/ListForeignKeys.sql:19
	WriteListForeignKeys(qb422016, schema)
//line queries/qsqlserver/ListForeignKeys.sql:19
	qs422016 := string(qb422016.B)
//line queries/qsqlserver/ListForeignKeys.sql:19
	qt422016.ReleaseByteBuffer(qb422016)
//line queries/qsqlserver/ListForeignKeys.sql:19
	return qs422016
//line queries/qsqlserver/ListForeignKeys.sql:19
}
