// Code generated by qtc from "ListIndexes.sql". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// --

//line queries/qsqlserver/ListIndexes.sql:1
package qsqlserver

//line queries/qsqlserver/ListIndexes.sql:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line queries/qsqlserver/ListIndexes.sql:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line queries/qsqlserver/ListIndexes.sql:1
func StreamListIndexes(qw422016 *qt422016.Writer, schema string) {
//line queries/qsqlserver/ListIndexes.sql:1
	qw422016.N().S(`
select schema_name(tab.schema_id) as [schema_name],
    tab.[name] as table_name,
    pk.[name] as index_name,
    substring(column_names, 1, len(column_names)-1) as [column_names],
    pk.is_primary_key as [pk],
    pk.is_unique as [u]
from sys.tables tab
  inner join sys.indexes pk
on tab.object_id = pk.object_id
  cross apply (select col.[name] + ', '
  from sys.index_columns ic
  inner join sys.columns col
  on ic.object_id = col.object_id
  and ic.column_id = col.column_id
  where ic.object_id = tab.object_id
  and ic.index_id = pk.index_id
  order by col.column_id
  for xml path ('') ) D (column_names)
order by schema_name(tab.schema_id), tab.[name], pk.[name];
-- `)
//line queries/qsqlserver/ListIndexes.sql:21
}

//line queries/qsqlserver/ListIndexes.sql:21
func WriteListIndexes(qq422016 qtio422016.Writer, schema string) {
//line queries/qsqlserver/ListIndexes.sql:21
	qw422016 := qt422016.AcquireWriter(qq422016)
//line queries/qsqlserver/ListIndexes.sql:21
	StreamListIndexes(qw422016, schema)
//line queries/qsqlserver/ListIndexes.sql:21
	qt422016.ReleaseWriter(qw422016)
//line queries/qsqlserver/ListIndexes.sql:21
}

//line queries/qsqlserver/ListIndexes.sql:21
func ListIndexes(schema string) string {
//line queries/qsqlserver/ListIndexes.sql:21
	qb422016 := qt422016.AcquireByteBuffer()
//line queries/qsqlserver/ListIndexes.sql:21
	WriteListIndexes(qb422016, schema)
//line queries/qsqlserver/ListIndexes.sql:21
	qs422016 := string(qb422016.B)
//line queries/qsqlserver/ListIndexes.sql:21
	qt422016.ReleaseByteBuffer(qb422016)
//line queries/qsqlserver/ListIndexes.sql:21
	return qs422016
//line queries/qsqlserver/ListIndexes.sql:21
}
