// Code generated by qtc from "Any.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/components/fieldview/Any.html:1
package fieldview

//line views/components/fieldview/Any.html:1
import (
	"fmt"
	"github.com/kyleu/admini/app/types"
)

//line views/components/fieldview/Any.html:6
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/components/fieldview/Any.html:6
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/components/fieldview/Any.html:6
func StreamAny(qw422016 *qt422016.Writer, x interface{}, t *types.Wrapped) {
//line views/components/fieldview/Any.html:7
	switch t.Key() {
//line views/components/fieldview/Any.html:8
	case "option":
//line views/components/fieldview/Any.html:9
		StreamOption(qw422016, x, t.T.(*types.Option))
//line views/components/fieldview/Any.html:10
	case "string":
//line views/components/fieldview/Any.html:11
		StreamString(qw422016, x.(string))
//line views/components/fieldview/Any.html:12
	case "json":
//line views/components/fieldview/Any.html:13
		StreamJSONInline(qw422016, x)
//line views/components/fieldview/Any.html:14
	case "int":
//line views/components/fieldview/Any.html:15
		StreamInt(qw422016, x)
//line views/components/fieldview/Any.html:16
	case "float":
//line views/components/fieldview/Any.html:17
		StreamFloat(qw422016, x)
//line views/components/fieldview/Any.html:18
	case "bool":
//line views/components/fieldview/Any.html:19
		StreamBoolean(qw422016, x.(bool))
//line views/components/fieldview/Any.html:20
	default:
//line views/components/fieldview/Any.html:21
		StreamDefault(qw422016, x, t.String())
//line views/components/fieldview/Any.html:22
	}
//line views/components/fieldview/Any.html:23
}

//line views/components/fieldview/Any.html:23
func WriteAny(qq422016 qtio422016.Writer, x interface{}, t *types.Wrapped) {
//line views/components/fieldview/Any.html:23
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/components/fieldview/Any.html:23
	StreamAny(qw422016, x, t)
//line views/components/fieldview/Any.html:23
	qt422016.ReleaseWriter(qw422016)
//line views/components/fieldview/Any.html:23
}

//line views/components/fieldview/Any.html:23
func Any(x interface{}, t *types.Wrapped) string {
//line views/components/fieldview/Any.html:23
	qb422016 := qt422016.AcquireByteBuffer()
//line views/components/fieldview/Any.html:23
	WriteAny(qb422016, x, t)
//line views/components/fieldview/Any.html:23
	qs422016 := string(qb422016.B)
//line views/components/fieldview/Any.html:23
	qt422016.ReleaseByteBuffer(qb422016)
//line views/components/fieldview/Any.html:23
	return qs422016
//line views/components/fieldview/Any.html:23
}

//line views/components/fieldview/Any.html:25
func StreamDefault(qw422016 *qt422016.Writer, x interface{}, t string) {
//line views/components/fieldview/Any.html:26
	msg := fmt.Sprintf("unhandled type: %s (%T)", t, x)

//line views/components/fieldview/Any.html:26
	qw422016.N().S(`<span title="`)
//line views/components/fieldview/Any.html:27
	qw422016.E().S(msg)
//line views/components/fieldview/Any.html:27
	qw422016.N().S(`">`)
//line views/components/fieldview/Any.html:27
	qw422016.E().V(x)
//line views/components/fieldview/Any.html:27
	qw422016.N().S(`</span>`)
//line views/components/fieldview/Any.html:28
}

//line views/components/fieldview/Any.html:28
func WriteDefault(qq422016 qtio422016.Writer, x interface{}, t string) {
//line views/components/fieldview/Any.html:28
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/components/fieldview/Any.html:28
	StreamDefault(qw422016, x, t)
//line views/components/fieldview/Any.html:28
	qt422016.ReleaseWriter(qw422016)
//line views/components/fieldview/Any.html:28
}

//line views/components/fieldview/Any.html:28
func Default(x interface{}, t string) string {
//line views/components/fieldview/Any.html:28
	qb422016 := qt422016.AcquireByteBuffer()
//line views/components/fieldview/Any.html:28
	WriteDefault(qb422016, x, t)
//line views/components/fieldview/Any.html:28
	qs422016 := string(qb422016.B)
//line views/components/fieldview/Any.html:28
	qt422016.ReleaseByteBuffer(qb422016)
//line views/components/fieldview/Any.html:28
	return qs422016
//line views/components/fieldview/Any.html:28
}
