// Code generated by qtc from "ArrayString.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/components/fieldview/ArrayString.html:1
package fieldview

//line views/components/fieldview/ArrayString.html:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/components/fieldview/ArrayString.html:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/components/fieldview/ArrayString.html:1
func StreamArrayString(qw422016 *qt422016.Writer, v []string) {
//line views/components/fieldview/ArrayString.html:2
	for idx, x := range v {
//line views/components/fieldview/ArrayString.html:3
		StreamString(qw422016, x)
//line views/components/fieldview/ArrayString.html:3
		if idx < len(v)-1 {
//line views/components/fieldview/ArrayString.html:3
			qw422016.N().S(`,`)
//line views/components/fieldview/ArrayString.html:3
			qw422016.N().S(` `)
//line views/components/fieldview/ArrayString.html:3
		}
//line views/components/fieldview/ArrayString.html:4
	}
//line views/components/fieldview/ArrayString.html:5
}

//line views/components/fieldview/ArrayString.html:5
func WriteArrayString(qq422016 qtio422016.Writer, v []string) {
//line views/components/fieldview/ArrayString.html:5
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/components/fieldview/ArrayString.html:5
	StreamArrayString(qw422016, v)
//line views/components/fieldview/ArrayString.html:5
	qt422016.ReleaseWriter(qw422016)
//line views/components/fieldview/ArrayString.html:5
}

//line views/components/fieldview/ArrayString.html:5
func ArrayString(v []string) string {
//line views/components/fieldview/ArrayString.html:5
	qb422016 := qt422016.AcquireByteBuffer()
//line views/components/fieldview/ArrayString.html:5
	WriteArrayString(qb422016, v)
//line views/components/fieldview/ArrayString.html:5
	qs422016 := string(qb422016.B)
//line views/components/fieldview/ArrayString.html:5
	qt422016.ReleaseByteBuffer(qb422016)
//line views/components/fieldview/ArrayString.html:5
	return qs422016
//line views/components/fieldview/ArrayString.html:5
}
