// Code generated by qtc from "Boolean.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/components/fieldview/Boolean.html:1
package fieldview

//line views/components/fieldview/Boolean.html:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/components/fieldview/Boolean.html:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/components/fieldview/Boolean.html:1
func StreamBoolean(qw422016 *qt422016.Writer, v bool) {
//line views/components/fieldview/Boolean.html:2
	if v {
//line views/components/fieldview/Boolean.html:2
		qw422016.N().S(`true`)
//line views/components/fieldview/Boolean.html:4
	} else {
//line views/components/fieldview/Boolean.html:4
		qw422016.N().S(`false`)
//line views/components/fieldview/Boolean.html:6
	}
//line views/components/fieldview/Boolean.html:7
}

//line views/components/fieldview/Boolean.html:7
func WriteBoolean(qq422016 qtio422016.Writer, v bool) {
//line views/components/fieldview/Boolean.html:7
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/components/fieldview/Boolean.html:7
	StreamBoolean(qw422016, v)
//line views/components/fieldview/Boolean.html:7
	qt422016.ReleaseWriter(qw422016)
//line views/components/fieldview/Boolean.html:7
}

//line views/components/fieldview/Boolean.html:7
func Boolean(v bool) string {
//line views/components/fieldview/Boolean.html:7
	qb422016 := qt422016.AcquireByteBuffer()
//line views/components/fieldview/Boolean.html:7
	WriteBoolean(qb422016, v)
//line views/components/fieldview/Boolean.html:7
	qs422016 := string(qb422016.B)
//line views/components/fieldview/Boolean.html:7
	qt422016.ReleaseByteBuffer(qb422016)
//line views/components/fieldview/Boolean.html:7
	return qs422016
//line views/components/fieldview/Boolean.html:7
}
