// Code generated by qtc from "Code.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/components/fieldview/Code.html:1
package fieldview

//line views/components/fieldview/Code.html:1
import (
	"github.com/kyleu/admini/app/controller/cutil"
)

//line views/components/fieldview/Code.html:5
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/components/fieldview/Code.html:5
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/components/fieldview/Code.html:5
func StreamCode(qw422016 *qt422016.Writer, content string, lang string) {
//line views/components/fieldview/Code.html:6
	out, err := cutil.FormatLang(content, lang)

//line views/components/fieldview/Code.html:7
	if err == nil {
//line views/components/fieldview/Code.html:7
		qw422016.N().S(out)
//line views/components/fieldview/Code.html:7
	} else {
//line views/components/fieldview/Code.html:7
		qw422016.E().S(err.Error())
//line views/components/fieldview/Code.html:7
	}
//line views/components/fieldview/Code.html:8
}

//line views/components/fieldview/Code.html:8
func WriteCode(qq422016 qtio422016.Writer, content string, lang string) {
//line views/components/fieldview/Code.html:8
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/components/fieldview/Code.html:8
	StreamCode(qw422016, content, lang)
//line views/components/fieldview/Code.html:8
	qt422016.ReleaseWriter(qw422016)
//line views/components/fieldview/Code.html:8
}

//line views/components/fieldview/Code.html:8
func Code(content string, lang string) string {
//line views/components/fieldview/Code.html:8
	qb422016 := qt422016.AcquireByteBuffer()
//line views/components/fieldview/Code.html:8
	WriteCode(qb422016, content, lang)
//line views/components/fieldview/Code.html:8
	qs422016 := string(qb422016.B)
//line views/components/fieldview/Code.html:8
	qt422016.ReleaseByteBuffer(qb422016)
//line views/components/fieldview/Code.html:8
	return qs422016
//line views/components/fieldview/Code.html:8
}
