// Code generated by qtc from "Int.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/components/fieldview/Int.html:1
package fieldview

//line views/components/fieldview/Int.html:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/components/fieldview/Int.html:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/components/fieldview/Int.html:1
func StreamInt(qw422016 *qt422016.Writer, v interface{}) {
//line views/components/fieldview/Int.html:2
	qw422016.E().V(v)
//line views/components/fieldview/Int.html:3
}

//line views/components/fieldview/Int.html:3
func WriteInt(qq422016 qtio422016.Writer, v interface{}) {
//line views/components/fieldview/Int.html:3
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/components/fieldview/Int.html:3
	StreamInt(qw422016, v)
//line views/components/fieldview/Int.html:3
	qt422016.ReleaseWriter(qw422016)
//line views/components/fieldview/Int.html:3
}

//line views/components/fieldview/Int.html:3
func Int(v interface{}) string {
//line views/components/fieldview/Int.html:3
	qb422016 := qt422016.AcquireByteBuffer()
//line views/components/fieldview/Int.html:3
	WriteInt(qb422016, v)
//line views/components/fieldview/Int.html:3
	qs422016 := string(qb422016.B)
//line views/components/fieldview/Int.html:3
	qt422016.ReleaseByteBuffer(qb422016)
//line views/components/fieldview/Int.html:3
	return qs422016
//line views/components/fieldview/Int.html:3
}
