// Code generated by qtc from "Option.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/components/fieldview/Option.html:1
package fieldview

//line views/components/fieldview/Option.html:1
import (
	"github.com/kyleu/admini/app/types"
)

//line views/components/fieldview/Option.html:5
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/components/fieldview/Option.html:5
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/components/fieldview/Option.html:5
func StreamOption(qw422016 *qt422016.Writer, x interface{}, t *types.Option) {
//line views/components/fieldview/Option.html:6
	if x == nil {
//line views/components/fieldview/Option.html:6
		qw422016.N().S(`<em>∅</em>`)
//line views/components/fieldview/Option.html:8
	} else {
//line views/components/fieldview/Option.html:9
		StreamAny(qw422016, x, t.V)
//line views/components/fieldview/Option.html:10
	}
//line views/components/fieldview/Option.html:11
}

//line views/components/fieldview/Option.html:11
func WriteOption(qq422016 qtio422016.Writer, x interface{}, t *types.Option) {
//line views/components/fieldview/Option.html:11
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/components/fieldview/Option.html:11
	StreamOption(qw422016, x, t)
//line views/components/fieldview/Option.html:11
	qt422016.ReleaseWriter(qw422016)
//line views/components/fieldview/Option.html:11
}

//line views/components/fieldview/Option.html:11
func Option(x interface{}, t *types.Option) string {
//line views/components/fieldview/Option.html:11
	qb422016 := qt422016.AcquireByteBuffer()
//line views/components/fieldview/Option.html:11
	WriteOption(qb422016, x, t)
//line views/components/fieldview/Option.html:11
	qs422016 := string(qb422016.B)
//line views/components/fieldview/Option.html:11
	qt422016.ReleaseByteBuffer(qb422016)
//line views/components/fieldview/Option.html:11
	return qs422016
//line views/components/fieldview/Option.html:11
}
