// Code generated by qtc from "listTables.sql". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// --

//line queries/listTables.sql:1
package queries

//line queries/listTables.sql:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line queries/listTables.sql:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line queries/listTables.sql:1
func StreamListTables(qw422016 *qt422016.Writer) {
//line queries/listTables.sql:1
	qw422016.N().S(`
select
  n.nspname as "schema",
  c.relname as "name",
  case c.relkind
    when 'r' then 'table'
    when 'v' then 'view'
    when 'm' then 'materialized view'
    when 'i' then 'index'
    when 'S' then 'sequence'
    when 's' then 'special'
    when 'f' then 'foreign table'
    when 'p' then 'partitioned table'
    when 'I' then 'partitioned index'
  end as "type",
  pg_catalog.pg_get_userbyid(c.relowner) as "owner"
from
  pg_catalog.pg_class c
  left join pg_catalog.pg_namespace n ON n.oid = c.relnamespace
where
  c.relkind IN ('r','p','v','m','S','f','')
  and n.nspname <> 'pg_catalog'
  and n.nspname <> 'information_schema'
  and n.nspname !~ '^pg_toast'
  and pg_catalog.pg_table_is_visible(c.oid)
order by
  "schema",
  "name"
;
-- `)
//line queries/listTables.sql:30
}

//line queries/listTables.sql:30
func WriteListTables(qq422016 qtio422016.Writer) {
//line queries/listTables.sql:30
	qw422016 := qt422016.AcquireWriter(qq422016)
//line queries/listTables.sql:30
	StreamListTables(qw422016)
//line queries/listTables.sql:30
	qt422016.ReleaseWriter(qw422016)
//line queries/listTables.sql:30
}

//line queries/listTables.sql:30
func ListTables() string {
//line queries/listTables.sql:30
	qb422016 := qt422016.AcquireByteBuffer()
//line queries/listTables.sql:30
	WriteListTables(qb422016)
//line queries/listTables.sql:30
	qs422016 := string(qb422016.B)
//line queries/listTables.sql:30
	qt422016.ReleaseByteBuffer(qb422016)
//line queries/listTables.sql:30
	return qs422016
//line queries/listTables.sql:30
}
