// Code generated by qtc from "Folder.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/vaction/Folder.html:1
package vaction

//line views/vaction/Folder.html:1
import (
	"admini.dev/app"
	"admini.dev/app/action"
	"admini.dev/app/controller/cutil"
	"admini.dev/views/layout"
)

//line views/vaction/Folder.html:8
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/vaction/Folder.html:8
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/vaction/Folder.html:8
type Folder struct {
	layout.Basic
	Req *cutil.WorkspaceRequest
	Act *action.Action
}

//line views/vaction/Folder.html:14
func (p *Folder) StreamBody(qw422016 *qt422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vaction/Folder.html:14
	qw422016.N().S(`
  <div class="card">
    `)
//line views/vaction/Folder.html:16
	StreamActionHeader(qw422016, p.Act, "Folder", ps)
//line views/vaction/Folder.html:16
	qw422016.N().S(`
  </div>
`)
//line views/vaction/Folder.html:18
	StreamResultChildren(qw422016, p.Req, p.Act, 1)
//line views/vaction/Folder.html:19
	StreamResultDebug(qw422016, p.Req, p.Act)
//line views/vaction/Folder.html:20
}

//line views/vaction/Folder.html:20
func (p *Folder) WriteBody(qq422016 qtio422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vaction/Folder.html:20
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vaction/Folder.html:20
	p.StreamBody(qw422016, as, ps)
//line views/vaction/Folder.html:20
	qt422016.ReleaseWriter(qw422016)
//line views/vaction/Folder.html:20
}

//line views/vaction/Folder.html:20
func (p *Folder) Body(as *app.State, ps *cutil.PageState) string {
//line views/vaction/Folder.html:20
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vaction/Folder.html:20
	p.WriteBody(qb422016, as, ps)
//line views/vaction/Folder.html:20
	qs422016 := string(qb422016.B)
//line views/vaction/Folder.html:20
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vaction/Folder.html:20
	return qs422016
//line views/vaction/Folder.html:20
}
