// Code generated by qtc from "Source.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/vaction/Source.html:1
package vaction

//line views/vaction/Source.html:1
import (
	"github.com/kyleu/admini/app"
	"github.com/kyleu/admini/app/action"
	"github.com/kyleu/admini/app/controller/cutil"
	"github.com/kyleu/admini/app/lib/schema/model"
	"github.com/kyleu/admini/app/source"
	"github.com/kyleu/admini/views/layout"
)

//line views/vaction/Source.html:10
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/vaction/Source.html:10
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/vaction/Source.html:10
type Source struct {
	layout.Basic
	Req    *cutil.WorkspaceRequest
	Act    *action.Action
	Source *source.Source
	Pkg    *model.Package
}

//line views/vaction/Source.html:18
func (p *Source) StreamBody(qw422016 *qt422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vaction/Source.html:18
	qw422016.N().S(`
  <div class="card">
    `)
//line views/vaction/Source.html:20
	StreamActionHeader(qw422016, p.Act, "Source", ps)
//line views/vaction/Source.html:20
	qw422016.N().S(`
`)
//line views/vaction/Source.html:21
	if len(p.Pkg.ChildPackages) > 0 {
//line views/vaction/Source.html:21
		qw422016.N().S(`    <ul>
`)
//line views/vaction/Source.html:23
		for _, pkg := range p.Pkg.ChildPackages {
//line views/vaction/Source.html:23
			qw422016.N().S(`      <li><a href="`)
//line views/vaction/Source.html:24
			qw422016.E().S(p.Req.RouteAct(p.Act, 0, pkg.Key))
//line views/vaction/Source.html:24
			qw422016.N().S(`">`)
//line views/vaction/Source.html:24
			qw422016.E().S(pkg.Name())
//line views/vaction/Source.html:24
			qw422016.N().S(`</a></li>
`)
//line views/vaction/Source.html:25
		}
//line views/vaction/Source.html:25
		qw422016.N().S(`    </ul>
`)
//line views/vaction/Source.html:27
	}
//line views/vaction/Source.html:27
	qw422016.N().S(`
`)
//line views/vaction/Source.html:29
	if len(p.Pkg.ChildModels) > 0 {
//line views/vaction/Source.html:29
		qw422016.N().S(`    <ul>
`)
//line views/vaction/Source.html:31
		for _, m := range p.Pkg.ChildModels {
//line views/vaction/Source.html:31
			qw422016.N().S(`      <li><a href="`)
//line views/vaction/Source.html:32
			qw422016.E().S(p.Req.RouteAct(p.Act, 0, m.Key))
//line views/vaction/Source.html:32
			qw422016.N().S(`">`)
//line views/vaction/Source.html:32
			qw422016.E().S(m.Name())
//line views/vaction/Source.html:32
			qw422016.N().S(`</a></li>
`)
//line views/vaction/Source.html:33
		}
//line views/vaction/Source.html:33
		qw422016.N().S(`    </ul>
`)
//line views/vaction/Source.html:35
	}
//line views/vaction/Source.html:35
	qw422016.N().S(`  </div>
`)
//line views/vaction/Source.html:37
	StreamResultChildren(qw422016, p.Req, p.Act, 1)
//line views/vaction/Source.html:38
	StreamResultDebug(qw422016, p.Req, p.Act)
//line views/vaction/Source.html:39
}

//line views/vaction/Source.html:39
func (p *Source) WriteBody(qq422016 qtio422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vaction/Source.html:39
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vaction/Source.html:39
	p.StreamBody(qw422016, as, ps)
//line views/vaction/Source.html:39
	qt422016.ReleaseWriter(qw422016)
//line views/vaction/Source.html:39
}

//line views/vaction/Source.html:39
func (p *Source) Body(as *app.State, ps *cutil.PageState) string {
//line views/vaction/Source.html:39
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vaction/Source.html:39
	p.WriteBody(qb422016, as, ps)
//line views/vaction/Source.html:39
	qs422016 := string(qb422016.B)
//line views/vaction/Source.html:39
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vaction/Source.html:39
	return qs422016
//line views/vaction/Source.html:39
}
