// Code generated by qtc from "Static.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/vaction/Static.html:1
package vaction

//line views/vaction/Static.html:1
import (
	"github.com/kyleu/admini/app"
	"github.com/kyleu/admini/app/action"
	"github.com/kyleu/admini/app/controller/cutil"
	"github.com/kyleu/admini/views/components"
	"github.com/kyleu/admini/views/layout"
)

//line views/vaction/Static.html:9
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/vaction/Static.html:9
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/vaction/Static.html:9
type Static struct {
	layout.Basic
	Req *cutil.WorkspaceRequest
	Act *action.Action
}

//line views/vaction/Static.html:15
func (p *Static) StreamBody(qw422016 *qt422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vaction/Static.html:15
	qw422016.N().S(`
  <div class="card">
    <div class="right"><a href="#modal-action"><button type="button">Action</button></a></div>
    <h3>`)
//line views/vaction/Static.html:18
	components.StreamSVGRef(qw422016, p.Act.IconWithFallback(), 20, 20, "icon", ps)
//line views/vaction/Static.html:18
	qw422016.E().S(p.Act.Name())
//line views/vaction/Static.html:18
	qw422016.N().S(`</h3>
    <em>Static</em>
  </div>
  <div class="card">
`)
//line views/vaction/Static.html:22
	ct := p.Act.Config.GetStringOpt("content")

//line views/vaction/Static.html:23
	switch p.Act.Config.GetStringOpt("format") {
//line views/vaction/Static.html:24
	case "html":
//line views/vaction/Static.html:24
		qw422016.N().S(`    `)
//line views/vaction/Static.html:25
		qw422016.N().S(ct)
//line views/vaction/Static.html:25
		qw422016.N().S(`
`)
//line views/vaction/Static.html:26
	case "text":
//line views/vaction/Static.html:26
		qw422016.N().S(`    `)
//line views/vaction/Static.html:27
		qw422016.E().S(ct)
//line views/vaction/Static.html:27
		qw422016.N().S(`
`)
//line views/vaction/Static.html:28
	case "code":
//line views/vaction/Static.html:28
		qw422016.N().S(`    <pre>`)
//line views/vaction/Static.html:29
		qw422016.E().S(ct)
//line views/vaction/Static.html:29
		qw422016.N().S(`</pre>
`)
//line views/vaction/Static.html:30
	default:
//line views/vaction/Static.html:30
		qw422016.N().S(`    `)
//line views/vaction/Static.html:31
		qw422016.E().S(ct)
//line views/vaction/Static.html:31
		qw422016.N().S(`
`)
//line views/vaction/Static.html:32
	}
//line views/vaction/Static.html:32
	qw422016.N().S(`  </div>
`)
//line views/vaction/Static.html:34
	StreamResultChildren(qw422016, p.Req, p.Act, 1)
//line views/vaction/Static.html:35
	StreamResultDebug(qw422016, p.Req, p.Act)
//line views/vaction/Static.html:36
}

//line views/vaction/Static.html:36
func (p *Static) WriteBody(qq422016 qtio422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vaction/Static.html:36
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vaction/Static.html:36
	p.StreamBody(qw422016, as, ps)
//line views/vaction/Static.html:36
	qt422016.ReleaseWriter(qw422016)
//line views/vaction/Static.html:36
}

//line views/vaction/Static.html:36
func (p *Static) Body(as *app.State, ps *cutil.PageState) string {
//line views/vaction/Static.html:36
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vaction/Static.html:36
	p.WriteBody(qb422016, as, ps)
//line views/vaction/Static.html:36
	qs422016 := string(qb422016.B)
//line views/vaction/Static.html:36
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vaction/Static.html:36
	return qs422016
//line views/vaction/Static.html:36
}
