// Code generated by qtc from "WSTable.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/vresult/WSTable.html:1
package vresult

//line views/vresult/WSTable.html:1
import (
	"fmt"

	"admini.dev/admini/app/action"
	"admini.dev/admini/app/controller/cutil"
	"admini.dev/admini/app/lib/filter"
	"admini.dev/admini/app/lib/schema/field"
	"admini.dev/admini/app/lib/schema/model"
	"admini.dev/admini/app/result"
	"admini.dev/admini/views/components"
	"admini.dev/admini/views/vutil"
)

//line views/vresult/WSTable.html:14
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/vresult/WSTable.html:14
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/vresult/WSTable.html:14
func StreamWSTable(qw422016 *qt422016.Writer, ws *cutil.WorkspaceRequest, act *action.Action, r *result.Result, m *model.Model, locs map[string]cutil.Locations, indent int, showNum bool, opts *filter.Options) {
//line views/vresult/WSTable.html:15
	vutil.StreamIndent(qw422016, true, indent)
//line views/vresult/WSTable.html:15
	qw422016.N().S(`<table class="result-table">`)
//line views/vresult/WSTable.html:17
	vutil.StreamIndent(qw422016, true, indent+1)
//line views/vresult/WSTable.html:17
	qw422016.N().S(`<thead>`)
//line views/vresult/WSTable.html:19
	vutil.StreamIndent(qw422016, true, indent+2)
//line views/vresult/WSTable.html:19
	qw422016.N().S(`<tr>`)
//line views/vresult/WSTable.html:21
	if showNum {
//line views/vresult/WSTable.html:22
		vutil.StreamIndent(qw422016, true, indent+3)
//line views/vresult/WSTable.html:22
		qw422016.N().S(`<th class="no-padding"><div class="resize"></div></th>`)
//line views/vresult/WSTable.html:24
	}
//line views/vresult/WSTable.html:25
	for fIdx, f := range r.Fields {
//line views/vresult/WSTable.html:26
		if m != nil && m.IsPK(f.Key, ws.PS.Logger) {
//line views/vresult/WSTable.html:27
			streamtableHeader(qw422016, ws, r, m, fIdx, f, locs[f.Key], true, indent+3, opts.Params)
//line views/vresult/WSTable.html:28
		}
//line views/vresult/WSTable.html:29
	}
//line views/vresult/WSTable.html:30
	for fIdx, f := range r.Fields {
//line views/vresult/WSTable.html:31
		if m == nil || !m.IsPK(f.Key, ws.PS.Logger) {
//line views/vresult/WSTable.html:32
			streamtableHeader(qw422016, ws, r, m, fIdx, f, locs[f.Key], false, indent+3, opts.Params)
//line views/vresult/WSTable.html:33
		}
//line views/vresult/WSTable.html:34
	}
//line views/vresult/WSTable.html:35
	vutil.StreamIndent(qw422016, true, indent+3)
//line views/vresult/WSTable.html:35
	qw422016.N().S(`<th class="tfill"></th>`)
//line views/vresult/WSTable.html:37
	vutil.StreamIndent(qw422016, true, indent+2)
//line views/vresult/WSTable.html:37
	qw422016.N().S(`</tr>`)
//line views/vresult/WSTable.html:39
	vutil.StreamIndent(qw422016, true, indent+1)
//line views/vresult/WSTable.html:39
	qw422016.N().S(`</thead>`)
//line views/vresult/WSTable.html:41
	vutil.StreamIndent(qw422016, true, indent+1)
//line views/vresult/WSTable.html:41
	qw422016.N().S(`<tbody>`)
//line views/vresult/WSTable.html:43
	for rIdx, row := range r.Data {
//line views/vresult/WSTable.html:44
		StreamWSRow(qw422016, ws, act, rIdx, row, r.Fields, m, indent+2, showNum)
//line views/vresult/WSTable.html:45
	}
//line views/vresult/WSTable.html:47
	if opts.Params.HasNextPage(r.Count) || opts.Params.HasPreviousPage() {
//line views/vresult/WSTable.html:48
		vutil.StreamIndent(qw422016, true, indent+2)
//line views/vresult/WSTable.html:48
		qw422016.N().S(`<tr><td colspan="`)
//line views/vresult/WSTable.html:49
		qw422016.N().D(len(r.Fields) + 1)
//line views/vresult/WSTable.html:49
		qw422016.N().S(`">`)
//line views/vresult/WSTable.html:49
		components.StreamPagination(qw422016, r.Count, opts.Params, ws.PS.URI)
//line views/vresult/WSTable.html:49
		qw422016.N().S(`</td></tr>`)
//line views/vresult/WSTable.html:50
	}
//line views/vresult/WSTable.html:51
	vutil.StreamIndent(qw422016, true, indent+1)
//line views/vresult/WSTable.html:51
	qw422016.N().S(`</tbody>`)
//line views/vresult/WSTable.html:53
	vutil.StreamIndent(qw422016, true, indent)
//line views/vresult/WSTable.html:53
	qw422016.N().S(`</table>`)
//line views/vresult/WSTable.html:55
}

//line views/vresult/WSTable.html:55
func WriteWSTable(qq422016 qtio422016.Writer, ws *cutil.WorkspaceRequest, act *action.Action, r *result.Result, m *model.Model, locs map[string]cutil.Locations, indent int, showNum bool, opts *filter.Options) {
//line views/vresult/WSTable.html:55
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vresult/WSTable.html:55
	StreamWSTable(qw422016, ws, act, r, m, locs, indent, showNum, opts)
//line views/vresult/WSTable.html:55
	qt422016.ReleaseWriter(qw422016)
//line views/vresult/WSTable.html:55
}

//line views/vresult/WSTable.html:55
func WSTable(ws *cutil.WorkspaceRequest, act *action.Action, r *result.Result, m *model.Model, locs map[string]cutil.Locations, indent int, showNum bool, opts *filter.Options) string {
//line views/vresult/WSTable.html:55
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vresult/WSTable.html:55
	WriteWSTable(qb422016, ws, act, r, m, locs, indent, showNum, opts)
//line views/vresult/WSTable.html:55
	qs422016 := string(qb422016.B)
//line views/vresult/WSTable.html:55
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vresult/WSTable.html:55
	return qs422016
//line views/vresult/WSTable.html:55
}

//line views/vresult/WSTable.html:57
func streamtableHeader(qw422016 *qt422016.Writer, ws *cutil.WorkspaceRequest, r *result.Result, m *model.Model, fIdx int, f *field.Field, locs cutil.Locations, pk bool, indent int, params *filter.Params) {
//line views/vresult/WSTable.html:58
	vutil.StreamIndent(qw422016, true, indent)
//line views/vresult/WSTable.html:60
	tooltip := fmt.Sprintf(`%s: ordinal %d (%s)`, f.Key, fIdx, f.Type)
	srt := m != nil && f.Type.Sortable()
	cls := ""
	icon := ""
	if pk {
		cls = "pkcol"
		icon = "lock"
	}

//line views/vresult/WSTable.html:69
	components.StreamTableHeader(qw422016, "x", f.Key, f.Name(), params, icon, ws.PS.URI, tooltip, srt, cls, true, ws.PS)
//line views/vresult/WSTable.html:70
}

//line views/vresult/WSTable.html:70
func writetableHeader(qq422016 qtio422016.Writer, ws *cutil.WorkspaceRequest, r *result.Result, m *model.Model, fIdx int, f *field.Field, locs cutil.Locations, pk bool, indent int, params *filter.Params) {
//line views/vresult/WSTable.html:70
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vresult/WSTable.html:70
	streamtableHeader(qw422016, ws, r, m, fIdx, f, locs, pk, indent, params)
//line views/vresult/WSTable.html:70
	qt422016.ReleaseWriter(qw422016)
//line views/vresult/WSTable.html:70
}

//line views/vresult/WSTable.html:70
func tableHeader(ws *cutil.WorkspaceRequest, r *result.Result, m *model.Model, fIdx int, f *field.Field, locs cutil.Locations, pk bool, indent int, params *filter.Params) string {
//line views/vresult/WSTable.html:70
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vresult/WSTable.html:70
	writetableHeader(qb422016, ws, r, m, fIdx, f, locs, pk, indent, params)
//line views/vresult/WSTable.html:70
	qs422016 := string(qb422016.B)
//line views/vresult/WSTable.html:70
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vresult/WSTable.html:70
	return qs422016
//line views/vresult/WSTable.html:70
}
