// Code generated by qtc from "Enum.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/vmodel/Enum.html:1
package vmodel

//line views/vmodel/Enum.html:1
import (
	"github.com/kyleu/admini/app"
	"github.com/kyleu/admini/app/action"
	"github.com/kyleu/admini/app/controller/cutil"
	"github.com/kyleu/admini/app/model"
	"github.com/kyleu/admini/views/components"
	"github.com/kyleu/admini/views/layout"
	"github.com/kyleu/admini/views/vaction"
)

//line views/vmodel/Enum.html:11
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/vmodel/Enum.html:11
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/vmodel/Enum.html:11
type Enum struct {
	layout.Basic
	Req   *cutil.WorkspaceRequest
	Act   *action.Action
	Model *model.Model
}

//line views/vmodel/Enum.html:18
func (p *Enum) StreamBody(qw422016 *qt422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vmodel/Enum.html:18
	qw422016.N().S(`
  <div class="card">
    <div class="right"><a href="#modal-action"><button type="button">Action</button></a></div>
    <h3>`)
//line views/vmodel/Enum.html:21
	components.StreamSVGRef(qw422016, p.Act.IconWithFallback(), 20, 20, "icon", ps)
//line views/vmodel/Enum.html:21
	qw422016.E().S(p.Act.Name())
//line views/vmodel/Enum.html:21
	qw422016.N().S(`</h3>
    <em>Model [`)
//line views/vmodel/Enum.html:22
	qw422016.E().S(p.Model.Name())
//line views/vmodel/Enum.html:22
	qw422016.N().S(`] (`)
//line views/vmodel/Enum.html:22
	qw422016.E().S(p.Model.Type.String())
//line views/vmodel/Enum.html:22
	qw422016.N().S(`)</em>
    <a href="#modal-model"><button type="button">Model</button></a>
  </div>

  <div class="card">
    <h3>Values</h3>
    <ul>
`)
//line views/vmodel/Enum.html:29
	for _, f := range p.Model.Fields {
//line views/vmodel/Enum.html:29
		qw422016.N().S(`      <li>`)
//line views/vmodel/Enum.html:30
		qw422016.E().S(f.Key)
//line views/vmodel/Enum.html:30
		qw422016.N().S(` <em>`)
//line views/vmodel/Enum.html:30
		qw422016.E().S(f.Description())
//line views/vmodel/Enum.html:30
		qw422016.N().S(`</em></li>
`)
//line views/vmodel/Enum.html:31
	}
//line views/vmodel/Enum.html:31
	qw422016.N().S(`    </ul>
  </div>

  `)
//line views/vmodel/Enum.html:35
	components.StreamJSONModal(qw422016, "model", "Model JSON", p.Model, 1)
//line views/vmodel/Enum.html:35
	qw422016.N().S(`
`)
//line views/vmodel/Enum.html:36
	vaction.StreamResultChildren(qw422016, p.Req, p.Act, 1)
//line views/vmodel/Enum.html:37
	vaction.StreamResultDebug(qw422016, p.Req, p.Act)
//line views/vmodel/Enum.html:38
}

//line views/vmodel/Enum.html:38
func (p *Enum) WriteBody(qq422016 qtio422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vmodel/Enum.html:38
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vmodel/Enum.html:38
	p.StreamBody(qw422016, as, ps)
//line views/vmodel/Enum.html:38
	qt422016.ReleaseWriter(qw422016)
//line views/vmodel/Enum.html:38
}

//line views/vmodel/Enum.html:38
func (p *Enum) Body(as *app.State, ps *cutil.PageState) string {
//line views/vmodel/Enum.html:38
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vmodel/Enum.html:38
	p.WriteBody(qb422016, as, ps)
//line views/vmodel/Enum.html:38
	qs422016 := string(qb422016.B)
//line views/vmodel/Enum.html:38
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vmodel/Enum.html:38
	return qs422016
//line views/vmodel/Enum.html:38
}
