// Code generated by qtc from "List.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/vmodel/List.html:1
package vmodel

//line views/vmodel/List.html:1
import (
	"admini.dev/admini/app"
	"admini.dev/admini/app/action"
	"admini.dev/admini/app/controller/cutil"
	"admini.dev/admini/app/lib/filter"
	"admini.dev/admini/app/lib/schema/model"
	"admini.dev/admini/app/result"
	"admini.dev/admini/views/components"
	"admini.dev/admini/views/layout"
	"admini.dev/admini/views/vaction"
	"admini.dev/admini/views/vresult"
)

//line views/vmodel/List.html:14
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/vmodel/List.html:14
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/vmodel/List.html:14
type List struct {
	layout.Basic
	Req     *cutil.WorkspaceRequest
	Act     *action.Action
	Model   *model.Model
	Options *filter.Options
	Result  *result.Result
}

//line views/vmodel/List.html:23
func (p *List) StreamBody(qw422016 *qt422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vmodel/List.html:23
	qw422016.N().S(`
  <div class="card card-sticky">
    `)
//line views/vmodel/List.html:25
	vaction.StreamActionHeader(qw422016, p.Act, "Model ["+p.Model.Name()+"] ("+p.Model.Type.String()+")", ps)
//line views/vmodel/List.html:25
	qw422016.N().S(`
    <a href="#modal-model"><button type="button">Model</button></a>
    <a href="#modal-result"><button type="button">Result</button></a>
    <a href="`)
//line views/vmodel/List.html:28
	qw422016.E().S(p.Req.RouteAct(p.Act, 0, `new`))
//line views/vmodel/List.html:28
	qw422016.N().S(`"><button type="button">Create New</button></a>
    <a href="`)
//line views/vmodel/List.html:29
	qw422016.E().S(p.Req.RouteAct(p.Act, 0, `export`))
//line views/vmodel/List.html:29
	qw422016.N().S(`"><button type="button">Export</button></a>
  </div>

  <div class="card card-sticky">
    `)
//line views/vmodel/List.html:33
	vresult.StreamWSOptions(qw422016, p.Req, p.Act, p.Result, p.Model, 2, p.Options)
//line views/vmodel/List.html:33
	qw422016.N().S(`
  </div>
  `)
//line views/vmodel/List.html:35
	vresult.StreamWSTable(qw422016, p.Req, p.Act, p.Result, p.Model, nil, 1, false, p.Options)
//line views/vmodel/List.html:35
	qw422016.N().S(`

`)
//line views/vmodel/List.html:37
	vaction.StreamResultChildren(qw422016, p.Req, p.Act, 1)
//line views/vmodel/List.html:38
	vaction.StreamResultDebug(qw422016, p.Req, p.Act)
//line views/vmodel/List.html:38
	qw422016.N().S(`  `)
//line views/vmodel/List.html:39
	components.StreamJSONModal(qw422016, "model", "Model JSON", p.Model, 1)
//line views/vmodel/List.html:39
	qw422016.N().S(`
  `)
//line views/vmodel/List.html:40
	components.StreamJSONModal(qw422016, "result", "Result", p.Result, 1)
//line views/vmodel/List.html:40
	qw422016.N().S(`
  `)
//line views/vmodel/List.html:41
	vresult.StreamWSModals(qw422016, p.Req, p.Act, p.Result, p.Model, 2, p.Options)
//line views/vmodel/List.html:41
	qw422016.N().S(`
`)
//line views/vmodel/List.html:42
}

//line views/vmodel/List.html:42
func (p *List) WriteBody(qq422016 qtio422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vmodel/List.html:42
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vmodel/List.html:42
	p.StreamBody(qw422016, as, ps)
//line views/vmodel/List.html:42
	qt422016.ReleaseWriter(qw422016)
//line views/vmodel/List.html:42
}

//line views/vmodel/List.html:42
func (p *List) Body(as *app.State, ps *cutil.PageState) string {
//line views/vmodel/List.html:42
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vmodel/List.html:42
	p.WriteBody(qb422016, as, ps)
//line views/vmodel/List.html:42
	qs422016 := string(qb422016.B)
//line views/vmodel/List.html:42
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vmodel/List.html:42
	return qs422016
//line views/vmodel/List.html:42
}
