// Code generated by qtc from "List.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/vmodel/List.html:1
package vmodel

//line views/vmodel/List.html:1
import (
	"github.com/kyleu/admini/app"
	"github.com/kyleu/admini/app/action"
	"github.com/kyleu/admini/app/controller/cutil"
	"github.com/kyleu/admini/app/filter"
	"github.com/kyleu/admini/app/model"
	"github.com/kyleu/admini/app/result"
	"github.com/kyleu/admini/views/components"
	"github.com/kyleu/admini/views/layout"
	"github.com/kyleu/admini/views/vaction"
	"github.com/kyleu/admini/views/vresult"
)

//line views/vmodel/List.html:14
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/vmodel/List.html:14
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/vmodel/List.html:14
type List struct {
	layout.Basic
	Req     *cutil.WorkspaceRequest
	Act     *action.Action
	Model   *model.Model
	Options *filter.Options
	Result  *result.Result
}

//line views/vmodel/List.html:23
func (p *List) StreamBody(qw422016 *qt422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vmodel/List.html:23
	qw422016.N().S(`
  <div class="card card-sticky">
    <div class="right"><a href="#modal-action"><button type="button">Action</button></a></div>
    <h3>`)
//line views/vmodel/List.html:26
	components.StreamSVGRef(qw422016, p.Act.IconWithFallback(), 20, 20, "icon", ps)
//line views/vmodel/List.html:26
	qw422016.E().S(p.Act.Name())
//line views/vmodel/List.html:26
	qw422016.N().S(`</h3>
    <em>Model [`)
//line views/vmodel/List.html:27
	qw422016.E().S(p.Model.Name())
//line views/vmodel/List.html:27
	qw422016.N().S(`] (`)
//line views/vmodel/List.html:27
	qw422016.E().S(p.Model.Type.String())
//line views/vmodel/List.html:27
	qw422016.N().S(`)</em>
    <a href="#modal-model"><button type="button">Model</button></a>
    <a href="#modal-result"><button type="button">Result</button></a>
    <a href="`)
//line views/vmodel/List.html:30
	qw422016.E().S(p.Req.RouteAct(p.Act, 0, `new`))
//line views/vmodel/List.html:30
	qw422016.N().S(`"><button type="button">Create New</button></a>
    <a href="`)
//line views/vmodel/List.html:31
	qw422016.E().S(p.Req.RouteAct(p.Act, 0, `export`))
//line views/vmodel/List.html:31
	qw422016.N().S(`"><button type="button">Export</button></a>
  </div>

  <div class="card card-sticky">
    `)
//line views/vmodel/List.html:35
	vresult.StreamWSOptions(qw422016, p.Req, p.Act, p.Result, p.Model, 2, p.Options)
//line views/vmodel/List.html:35
	qw422016.N().S(`
  </div>
  `)
//line views/vmodel/List.html:37
	vresult.StreamWSTable(qw422016, p.Req, p.Act, p.Result, p.Model, nil, 1, false, p.Options)
//line views/vmodel/List.html:37
	qw422016.N().S(`

`)
//line views/vmodel/List.html:39
	vaction.StreamResultChildren(qw422016, p.Req, p.Act, 1)
//line views/vmodel/List.html:40
	vaction.StreamResultDebug(qw422016, p.Req, p.Act)
//line views/vmodel/List.html:40
	qw422016.N().S(`  `)
//line views/vmodel/List.html:41
	components.StreamJSONModal(qw422016, "model", "Model JSON", p.Model, 1)
//line views/vmodel/List.html:41
	qw422016.N().S(`
  `)
//line views/vmodel/List.html:42
	components.StreamJSONModal(qw422016, "result", "Result", p.Result, 1)
//line views/vmodel/List.html:42
	qw422016.N().S(`
  `)
//line views/vmodel/List.html:43
	vresult.StreamWSModals(qw422016, p.Req, p.Act, p.Result, p.Model, 2, p.Options)
//line views/vmodel/List.html:43
	qw422016.N().S(`
`)
//line views/vmodel/List.html:44
}

//line views/vmodel/List.html:44
func (p *List) WriteBody(qq422016 qtio422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vmodel/List.html:44
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vmodel/List.html:44
	p.StreamBody(qw422016, as, ps)
//line views/vmodel/List.html:44
	qt422016.ReleaseWriter(qw422016)
//line views/vmodel/List.html:44
}

//line views/vmodel/List.html:44
func (p *List) Body(as *app.State, ps *cutil.PageState) string {
//line views/vmodel/List.html:44
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vmodel/List.html:44
	p.WriteBody(qb422016, as, ps)
//line views/vmodel/List.html:44
	qs422016 := string(qb422016.B)
//line views/vmodel/List.html:44
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vmodel/List.html:44
	return qs422016
//line views/vmodel/List.html:44
}
