// Code generated by qtc from "View.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/vmodel/View.html:1
package vmodel

//line views/vmodel/View.html:1
import (
	"github.com/kyleu/admini/app"
	"github.com/kyleu/admini/app/action"
	"github.com/kyleu/admini/app/controller/cutil"
	"github.com/kyleu/admini/app/filter"
	"github.com/kyleu/admini/app/model"
	"github.com/kyleu/admini/app/qualify"
	"github.com/kyleu/admini/app/util"
	"github.com/kyleu/admini/views/components"
	"github.com/kyleu/admini/views/components/fieldview"
	"github.com/kyleu/admini/views/layout"
	"github.com/kyleu/admini/views/vresult"
	"strings"
)

//line views/vmodel/View.html:16
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/vmodel/View.html:16
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/vmodel/View.html:16
type View struct {
	layout.Basic
	Req    *cutil.WorkspaceRequest
	Act    *action.Action
	Model  *model.Model
	Result []interface{}
}

//line views/vmodel/View.html:24
func (p *View) StreamBody(qw422016 *qt422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vmodel/View.html:24
	qw422016.N().S(`
  <div class="card">
`)
//line views/vmodel/View.html:27
	rowPK, err := model.GetStrings(p.Model.Fields, p.Model.GetPK(ps.Logger), p.Result)
	if err != nil {
		panic(err)
	}

//line views/vmodel/View.html:31
	qw422016.N().S(`    <div class="right"><a href="`)
//line views/vmodel/View.html:32
	qw422016.E().S(p.Req.RouteAct(p.Act, 1+len(rowPK), append([]string{`x`}, rowPK...)...))
//line views/vmodel/View.html:32
	qw422016.N().S(`">Edit</a></div>
    <h3>`)
//line views/vmodel/View.html:33
	components.StreamSVGRef(qw422016, p.Act.IconWithFallback(), 20, 20, "icon", ps)
//line views/vmodel/View.html:33
	qw422016.E().S(strings.Join(rowPK, "/"))
//line views/vmodel/View.html:33
	qw422016.N().S(`</h3>
    <a href="`)
//line views/vmodel/View.html:34
	qw422016.E().S(p.Req.RouteAct(p.Act, len(rowPK)+1))
//line views/vmodel/View.html:34
	qw422016.N().S(`"><em>`)
//line views/vmodel/View.html:34
	qw422016.E().S(p.Model.Name())
//line views/vmodel/View.html:34
	qw422016.N().S(`</em></a>
  </div>
  <div class="card">
    <table>
      <tbody>
`)
//line views/vmodel/View.html:39
	for idx, f := range p.Model.Fields {
//line views/vmodel/View.html:39
		qw422016.N().S(`        <tr>
          <th class="shrink">`)
//line views/vmodel/View.html:41
		qw422016.E().S(f.Name())
//line views/vmodel/View.html:41
		qw422016.N().S(`</th>
          <td>
            `)
//line views/vmodel/View.html:43
		fieldview.StreamAny(qw422016, p.Result[idx], f.Type)
//line views/vmodel/View.html:43
		qw422016.N().S(`
`)
//line views/vmodel/View.html:44
		for _, rel := range p.Model.ApplicableRelations(f.Key) {
//line views/vmodel/View.html:46
			results, err := qualify.Handle(rel, p.Act, p.Req, p.Model, p.Result)
			if err != nil {
				panic(err)
			}

//line views/vmodel/View.html:51
			for _, r := range results {
//line views/vmodel/View.html:51
				qw422016.N().S(`            <a href="`)
//line views/vmodel/View.html:52
				qw422016.E().S(p.Req.Route(r.String()))
//line views/vmodel/View.html:52
				qw422016.N().S(`">`)
//line views/vmodel/View.html:52
				components.StreamSVGRef(qw422016, r.Icon, 16, 16, ``, ps)
//line views/vmodel/View.html:52
				qw422016.N().S(`</a>
`)
//line views/vmodel/View.html:53
			}
//line views/vmodel/View.html:54
			for _, r := range results {
//line views/vmodel/View.html:54
				qw422016.N().S(`            <div>
`)
//line views/vmodel/View.html:57
				// TODO: Replace with actual table, you've already got the model and data

//line views/vmodel/View.html:58
				qw422016.N().S(`              `)
//line views/vmodel/View.html:59
				vresult.StreamWSTable(qw422016, p.Req, r.Action, r.ToResult(), r.Model, nil, 4, false, &filter.Options{})
//line views/vmodel/View.html:59
				qw422016.N().S(`
              <pre>`)
//line views/vmodel/View.html:60
				qw422016.E().S(util.ToJSON(r))
//line views/vmodel/View.html:60
				qw422016.N().S(`</pre>
            </div>
`)
//line views/vmodel/View.html:62
			}
//line views/vmodel/View.html:63
		}
//line views/vmodel/View.html:63
		qw422016.N().S(`          </td>
        </tr>
`)
//line views/vmodel/View.html:66
	}
//line views/vmodel/View.html:66
	qw422016.N().S(`      </tbody>
    </table>
  </div>
`)
//line views/vmodel/View.html:70
	if len(p.Model.References) > 0 {
//line views/vmodel/View.html:70
		qw422016.N().S(`  <div class="card">
    <h3>References</h3>
    <ul class="accordion">
`)
//line views/vmodel/View.html:74
		for _, r := range p.Model.References {
//line views/vmodel/View.html:74
			qw422016.N().S(`      <li>
        <input id="`)
//line views/vmodel/View.html:76
			qw422016.E().S(r.Key)
//line views/vmodel/View.html:76
			qw422016.N().S(`-count" type="checkbox" hidden />
        <label for="`)
//line views/vmodel/View.html:77
			qw422016.E().S(r.Key)
//line views/vmodel/View.html:77
			qw422016.N().S(`-count">`)
//line views/vmodel/View.html:77
			components.StreamExpandCollapse(qw422016, 3, ps)
//line views/vmodel/View.html:77
			qw422016.N().S(` `)
//line views/vmodel/View.html:77
			qw422016.E().S(r.String())
//line views/vmodel/View.html:77
			qw422016.N().S(`</label>
        <div class="bd">
          <div>TODO</div>
        </div>
      </li>
`)
//line views/vmodel/View.html:82
		}
//line views/vmodel/View.html:82
		qw422016.N().S(`    </ul>
  </div>
`)
//line views/vmodel/View.html:85
	}
//line views/vmodel/View.html:86
}

//line views/vmodel/View.html:86
func (p *View) WriteBody(qq422016 qtio422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vmodel/View.html:86
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vmodel/View.html:86
	p.StreamBody(qw422016, as, ps)
//line views/vmodel/View.html:86
	qt422016.ReleaseWriter(qw422016)
//line views/vmodel/View.html:86
}

//line views/vmodel/View.html:86
func (p *View) Body(as *app.State, ps *cutil.PageState) string {
//line views/vmodel/View.html:86
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vmodel/View.html:86
	p.WriteBody(qb422016, as, ps)
//line views/vmodel/View.html:86
	qs422016 := string(qb422016.B)
//line views/vmodel/View.html:86
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vmodel/View.html:86
	return qs422016
//line views/vmodel/View.html:86
}
