// Code generated by qtc from "ListColumns.sql". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// --

//line queries/qmysql/ListColumns.sql:1
package qmysql

//line queries/qmysql/ListColumns.sql:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line queries/qmysql/ListColumns.sql:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line queries/qmysql/ListColumns.sql:1
func StreamListColumns(qw422016 *qt422016.Writer, schema string) {
//line queries/qmysql/ListColumns.sql:1
	qw422016.N().S(`
select
  c.table_schema,
  c.table_name,
  c.column_name,
  c.ordinal_position,
  c.column_default,
  c.is_nullable,
  c.data_type,
  c.character_maximum_length,
  c.character_octet_length,
  c.numeric_precision,
  c.numeric_scale,
  c.datetime_precision
from
  information_schema.columns c
where
  c.table_schema not in ('information_schema', 'pg_catalog')
  `)
//line queries/qmysql/ListColumns.sql:19
	if schema != "" {
//line queries/qmysql/ListColumns.sql:19
		qw422016.N().S(` and c.table_schema = '`)
//line queries/qmysql/ListColumns.sql:19
		qw422016.E().S(schema)
//line queries/qmysql/ListColumns.sql:19
		qw422016.N().S(`'`)
//line queries/qmysql/ListColumns.sql:19
	}
//line queries/qmysql/ListColumns.sql:19
	qw422016.N().S(`
order by
  c.table_schema, c.table_name, c.ordinal_position;
-- `)
//line queries/qmysql/ListColumns.sql:22
}

//line queries/qmysql/ListColumns.sql:22
func WriteListColumns(qq422016 qtio422016.Writer, schema string) {
//line queries/qmysql/ListColumns.sql:22
	qw422016 := qt422016.AcquireWriter(qq422016)
//line queries/qmysql/ListColumns.sql:22
	StreamListColumns(qw422016, schema)
//line queries/qmysql/ListColumns.sql:22
	qt422016.ReleaseWriter(qw422016)
//line queries/qmysql/ListColumns.sql:22
}

//line queries/qmysql/ListColumns.sql:22
func ListColumns(schema string) string {
//line queries/qmysql/ListColumns.sql:22
	qb422016 := qt422016.AcquireByteBuffer()
//line queries/qmysql/ListColumns.sql:22
	WriteListColumns(qb422016, schema)
//line queries/qmysql/ListColumns.sql:22
	qs422016 := string(qb422016.B)
//line queries/qmysql/ListColumns.sql:22
	qt422016.ReleaseByteBuffer(qb422016)
//line queries/qmysql/ListColumns.sql:22
	return qs422016
//line queries/qmysql/ListColumns.sql:22
}
