// Code generated by projectforge.dev using code from the [desktop] module, which is under license [CC0]
module github.com/kyleu/admini/tools/desktop

go 1.15

require (
	github.com/kyleu/admini v0.0.0
	github.com/webview/webview v0.0.0-20210330151455-f540d88dde4e
)

replace github.com/kyleu/admini => ../..
