// Code generated by qtc from "Detail.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/vsource/Detail.html:1
package vsource

//line views/vsource/Detail.html:1
import (
	"github.com/kyleu/admini/app"
	"github.com/kyleu/admini/app/controller/cutil"
	"github.com/kyleu/admini/app/model"
	"github.com/kyleu/admini/app/schema"
	"github.com/kyleu/admini/app/source"
	"github.com/kyleu/admini/app/util"
	"github.com/kyleu/admini/views/components"
	"github.com/kyleu/admini/views/layout"
	"github.com/kyleu/admini/views/vutil"
)

//line views/vsource/Detail.html:13
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/vsource/Detail.html:13
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/vsource/Detail.html:13
type Detail struct {
	layout.Basic
	Source *source.Source
	Schema *schema.Schema
}

//line views/vsource/Detail.html:19
func (p *Detail) StreamBody(qw422016 *qt422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vsource/Detail.html:19
	qw422016.N().S(`
  <div class="card">
    <div class="right"><a href="/source/`)
//line views/vsource/Detail.html:21
	qw422016.E().S(p.Source.Key)
//line views/vsource/Detail.html:21
	qw422016.N().S(`/edit"><button type="button">Edit</button></a></div>
    <h3>`)
//line views/vsource/Detail.html:22
	components.StreamSVGRef(qw422016, p.Source.IconWithFallback(), 20, 20, `icon`, ps)
//line views/vsource/Detail.html:22
	qw422016.E().S(p.Source.Name())
//line views/vsource/Detail.html:22
	qw422016.N().S(`</h3>
    `)
//line views/vsource/Detail.html:23
	if p.Source.Description != "" {
//line views/vsource/Detail.html:23
		qw422016.N().S(`<em>`)
//line views/vsource/Detail.html:23
		qw422016.E().S(p.Source.Description)
//line views/vsource/Detail.html:23
		qw422016.N().S(`</em>`)
//line views/vsource/Detail.html:23
	}
//line views/vsource/Detail.html:23
	qw422016.N().S(`
    <p>
      <a href="/s/`)
//line views/vsource/Detail.html:25
	qw422016.E().S(p.Source.Key)
//line views/vsource/Detail.html:25
	qw422016.N().S(`"><button type="button">Workspace</button></a>
      <a href="/source/`)
//line views/vsource/Detail.html:26
	qw422016.E().S(p.Source.Key)
//line views/vsource/Detail.html:26
	qw422016.N().S(`/refresh"><button type="button">Refresh</button></a>
    </p>
  </div>

  <div class="card">
    <h3>Models</h3>
    <table>
      <thead>
        <tr>
          <th>Key</th>
          <th>Title</th>
          <th>Plural</th>
          <th>Path</th>
        </tr>
      </thead>
      <tbody>
`)
//line views/vsource/Detail.html:42
	if p.Schema != nil && len(p.Schema.Models) > 0 {
//line views/vsource/Detail.html:43
		for _, m := range p.Schema.Models {
//line views/vsource/Detail.html:43
			qw422016.N().S(`        `)
//line views/vsource/Detail.html:44
			streammodelRow(qw422016, p.Source.Key, m, 4, as, ps)
//line views/vsource/Detail.html:44
			qw422016.N().S(`
`)
//line views/vsource/Detail.html:45
		}
//line views/vsource/Detail.html:46
	} else {
//line views/vsource/Detail.html:46
		qw422016.N().S(`        <tr><td colspan="3"><em>no models</em></td></tr>
`)
//line views/vsource/Detail.html:48
	}
//line views/vsource/Detail.html:48
	qw422016.N().S(`      </tbody>
    </table>
  </div>
`)
//line views/vsource/Detail.html:52
}

//line views/vsource/Detail.html:52
func (p *Detail) WriteBody(qq422016 qtio422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vsource/Detail.html:52
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vsource/Detail.html:52
	p.StreamBody(qw422016, as, ps)
//line views/vsource/Detail.html:52
	qt422016.ReleaseWriter(qw422016)
//line views/vsource/Detail.html:52
}

//line views/vsource/Detail.html:52
func (p *Detail) Body(as *app.State, ps *cutil.PageState) string {
//line views/vsource/Detail.html:52
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vsource/Detail.html:52
	p.WriteBody(qb422016, as, ps)
//line views/vsource/Detail.html:52
	qs422016 := string(qb422016.B)
//line views/vsource/Detail.html:52
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vsource/Detail.html:52
	return qs422016
//line views/vsource/Detail.html:52
}

//line views/vsource/Detail.html:54
func streammodelRow(qw422016 *qt422016.Writer, srcKey string, m *model.Model, indent int, as *app.State, ps *cutil.PageState) {
//line views/vsource/Detail.html:54
	qw422016.N().S(`<tr>`)
//line views/vsource/Detail.html:56
	vutil.StreamIndent(qw422016, true, indent+1)
//line views/vsource/Detail.html:56
	qw422016.N().S(`<td><a href="/source/`)
//line views/vsource/Detail.html:57
	qw422016.E().S(srcKey)
//line views/vsource/Detail.html:57
	qw422016.N().S(`/model/`)
//line views/vsource/Detail.html:57
	qw422016.E().S(m.String())
//line views/vsource/Detail.html:57
	qw422016.N().S(`">`)
//line views/vsource/Detail.html:57
	qw422016.E().S(m.Key)
//line views/vsource/Detail.html:57
	qw422016.N().S(`</a></td>`)
//line views/vsource/Detail.html:58
	vutil.StreamIndent(qw422016, true, indent+1)
//line views/vsource/Detail.html:60
	sing, plur := util.StringForms(util.ToTitle(m.Key))

//line views/vsource/Detail.html:60
	qw422016.N().S(`<td>`)
//line views/vsource/Detail.html:62
	if m.Name() == sing {
//line views/vsource/Detail.html:62
		qw422016.N().S(`<em>`)
//line views/vsource/Detail.html:63
		qw422016.E().S(m.Name())
//line views/vsource/Detail.html:63
		qw422016.N().S(`</em>`)
//line views/vsource/Detail.html:64
	} else {
//line views/vsource/Detail.html:65
		qw422016.E().S(m.Name())
//line views/vsource/Detail.html:66
	}
//line views/vsource/Detail.html:66
	qw422016.N().S(`</td>`)
//line views/vsource/Detail.html:68
	vutil.StreamIndent(qw422016, true, indent+1)
//line views/vsource/Detail.html:68
	qw422016.N().S(`<td>`)
//line views/vsource/Detail.html:70
	if m.PluralName() == plur {
//line views/vsource/Detail.html:70
		qw422016.N().S(`<em>`)
//line views/vsource/Detail.html:71
		qw422016.E().S(m.PluralName())
//line views/vsource/Detail.html:71
		qw422016.N().S(`</em>`)
//line views/vsource/Detail.html:72
	} else {
//line views/vsource/Detail.html:73
		qw422016.E().S(m.PluralName())
//line views/vsource/Detail.html:74
	}
//line views/vsource/Detail.html:74
	qw422016.N().S(`</td>`)
//line views/vsource/Detail.html:76
	vutil.StreamIndent(qw422016, true, indent+1)
//line views/vsource/Detail.html:76
	qw422016.N().S(`<td>`)
//line views/vsource/Detail.html:77
	qw422016.E().S(m.Pkg.ToPath())
//line views/vsource/Detail.html:77
	qw422016.N().S(`</td>`)
//line views/vsource/Detail.html:78
	vutil.StreamIndent(qw422016, true, indent)
//line views/vsource/Detail.html:78
	qw422016.N().S(`</tr>`)
//line views/vsource/Detail.html:80
}

//line views/vsource/Detail.html:80
func writemodelRow(qq422016 qtio422016.Writer, srcKey string, m *model.Model, indent int, as *app.State, ps *cutil.PageState) {
//line views/vsource/Detail.html:80
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vsource/Detail.html:80
	streammodelRow(qw422016, srcKey, m, indent, as, ps)
//line views/vsource/Detail.html:80
	qt422016.ReleaseWriter(qw422016)
//line views/vsource/Detail.html:80
}

//line views/vsource/Detail.html:80
func modelRow(srcKey string, m *model.Model, indent int, as *app.State, ps *cutil.PageState) string {
//line views/vsource/Detail.html:80
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vsource/Detail.html:80
	writemodelRow(qb422016, srcKey, m, indent, as, ps)
//line views/vsource/Detail.html:80
	qs422016 := string(qb422016.B)
//line views/vsource/Detail.html:80
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vsource/Detail.html:80
	return qs422016
//line views/vsource/Detail.html:80
}
