// Code generated by qtc from "ModelReferenceList.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/vsource/ModelReferenceList.html:1
package vsource

//line views/vsource/ModelReferenceList.html:1
import (
	"admini.dev/admini/app"
	"admini.dev/admini/app/controller/cutil"
	"admini.dev/admini/app/lib/schema/model"
	"admini.dev/admini/app/util"
	"admini.dev/admini/views/components/fieldview"
)

//line views/vsource/ModelReferenceList.html:9
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/vsource/ModelReferenceList.html:9
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/vsource/ModelReferenceList.html:9
func StreamModelReferenceList(qw422016 *qt422016.Writer, m *model.Model, as *app.State, ps *cutil.PageState) {
//line views/vsource/ModelReferenceList.html:9
	if len(m.References) > 0 {
//line views/vsource/ModelReferenceList.html:9
		qw422016.N().S(`    <div class="card">
      <h3>`)
//line views/vsource/ModelReferenceList.html:11
		qw422016.E().S(util.StringPlural(len(m.References), `reference`))
//line views/vsource/ModelReferenceList.html:11
		qw422016.N().S(`</h3>
      <table>
        <thead>
          <tr>
            <th>Key</th>
            <th>Target Fields</th>
            <th>Source Package</th>
            <th>Source Model</th>
            <th>Source Fields</th>
          </tr>
        </thead>
        <tbody>
`)
//line views/vsource/ModelReferenceList.html:23
		for _, ref := range m.References {
//line views/vsource/ModelReferenceList.html:23
			qw422016.N().S(`          <tr>
            <td>`)
//line views/vsource/ModelReferenceList.html:25
			fieldview.StreamString(qw422016, ref.Key)
//line views/vsource/ModelReferenceList.html:25
			qw422016.N().S(`</td>
            <td>`)
//line views/vsource/ModelReferenceList.html:26
			fieldview.StreamArrayString(qw422016, ref.TargetFields)
//line views/vsource/ModelReferenceList.html:26
			qw422016.N().S(`</td>
            <td>`)
//line views/vsource/ModelReferenceList.html:27
			fieldview.StreamPackage(qw422016, ref.SourcePkg)
//line views/vsource/ModelReferenceList.html:27
			qw422016.N().S(`</td>
            <td>`)
//line views/vsource/ModelReferenceList.html:28
			fieldview.StreamString(qw422016, ref.SourceModel)
//line views/vsource/ModelReferenceList.html:28
			qw422016.N().S(`</td>
            <td>`)
//line views/vsource/ModelReferenceList.html:29
			fieldview.StreamArrayString(qw422016, ref.SourceFields)
//line views/vsource/ModelReferenceList.html:29
			qw422016.N().S(`</td>
          </tr>
`)
//line views/vsource/ModelReferenceList.html:31
		}
//line views/vsource/ModelReferenceList.html:31
		qw422016.N().S(`        </tbody>
      </table>
    </div>
`)
//line views/vsource/ModelReferenceList.html:35
	}
//line views/vsource/ModelReferenceList.html:35
}

//line views/vsource/ModelReferenceList.html:35
func WriteModelReferenceList(qq422016 qtio422016.Writer, m *model.Model, as *app.State, ps *cutil.PageState) {
//line views/vsource/ModelReferenceList.html:35
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vsource/ModelReferenceList.html:35
	StreamModelReferenceList(qw422016, m, as, ps)
//line views/vsource/ModelReferenceList.html:35
	qt422016.ReleaseWriter(qw422016)
//line views/vsource/ModelReferenceList.html:35
}

//line views/vsource/ModelReferenceList.html:35
func ModelReferenceList(m *model.Model, as *app.State, ps *cutil.PageState) string {
//line views/vsource/ModelReferenceList.html:35
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vsource/ModelReferenceList.html:35
	WriteModelReferenceList(qb422016, m, as, ps)
//line views/vsource/ModelReferenceList.html:35
	qs422016 := string(qb422016.B)
//line views/vsource/ModelReferenceList.html:35
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vsource/ModelReferenceList.html:35
	return qs422016
//line views/vsource/ModelReferenceList.html:35
}
