// Code generated by qtc from "ModelFieldList.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/vsource/ModelFieldList.html:1
package vsource

//line views/vsource/ModelFieldList.html:1
import (
	"fmt"
	"github.com/kyleu/admini/app"
	"github.com/kyleu/admini/app/controller/cutil"
	"github.com/kyleu/admini/app/model"
	"github.com/kyleu/admini/app/util"
	"github.com/kyleu/admini/views/components"
	"github.com/kyleu/admini/views/components/fieldview"
)

//line views/vsource/ModelFieldList.html:11
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/vsource/ModelFieldList.html:11
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/vsource/ModelFieldList.html:11
func StreamModelFieldList(qw422016 *qt422016.Writer, m *model.Model, as *app.State, ps *cutil.PageState) {
//line views/vsource/ModelFieldList.html:11
	if len(m.Fields) > 0 {
//line views/vsource/ModelFieldList.html:11
		qw422016.N().S(`    <div class="card">
      <h3>`)
//line views/vsource/ModelFieldList.html:13
		qw422016.E().S(util.Plural(len(m.Fields), `field`))
//line views/vsource/ModelFieldList.html:13
		qw422016.N().S(`</h3>
      <table>
        <thead>
          <tr>
            <th>Key</th>
            <th>Title</th>
            <th>Plural</th>
            <th>Type</th>
          </tr>
        </thead>
        <tbody>
`)
//line views/vsource/ModelFieldList.html:24
		for _, f := range m.Fields {
//line views/vsource/ModelFieldList.html:25
			sing, plur := util.StringForms(util.ToTitle(f.Key))

//line views/vsource/ModelFieldList.html:25
			qw422016.N().S(`          <tr>
            <td>`)
//line views/vsource/ModelFieldList.html:27
			fieldview.StreamString(qw422016, f.Key)
//line views/vsource/ModelFieldList.html:27
			qw422016.N().S(`</td>
            <td>
              <div class="toggle">
                <input id="toggle-`)
//line views/vsource/ModelFieldList.html:30
			qw422016.E().S(f.Key)
//line views/vsource/ModelFieldList.html:30
			qw422016.N().S(`-title" type="checkbox" hidden />
                <label for="toggle-`)
//line views/vsource/ModelFieldList.html:31
			qw422016.E().S(f.Key)
//line views/vsource/ModelFieldList.html:31
			qw422016.N().S(`-title">
`)
//line views/vsource/ModelFieldList.html:32
			if f.Name() == sing {
//line views/vsource/ModelFieldList.html:32
				qw422016.N().S(`                  <em>`)
//line views/vsource/ModelFieldList.html:33
				qw422016.E().S(f.Name())
//line views/vsource/ModelFieldList.html:33
				qw422016.N().S(`</em>
`)
//line views/vsource/ModelFieldList.html:34
			} else {
//line views/vsource/ModelFieldList.html:34
				qw422016.N().S(`                  `)
//line views/vsource/ModelFieldList.html:35
				qw422016.E().S(f.Name())
//line views/vsource/ModelFieldList.html:35
				qw422016.N().S(`
`)
//line views/vsource/ModelFieldList.html:36
			}
//line views/vsource/ModelFieldList.html:36
			qw422016.N().S(`                </label>
                <div class="x">
                  `)
//line views/vsource/ModelFieldList.html:39
			components.StreamFormInput(qw422016, fmt.Sprintf("f.%s.title", f.Key), f.Key+"-title", f.Name())
//line views/vsource/ModelFieldList.html:39
			qw422016.N().S(`
                </div>
              </div>
            </td>
            <td>
              <div class="toggle">
                <input id="toggle-`)
//line views/vsource/ModelFieldList.html:45
			qw422016.E().S(f.Key)
//line views/vsource/ModelFieldList.html:45
			qw422016.N().S(`-plural" type="checkbox" hidden />
                <label for="toggle-`)
//line views/vsource/ModelFieldList.html:46
			qw422016.E().S(f.Key)
//line views/vsource/ModelFieldList.html:46
			qw422016.N().S(`-plural">
`)
//line views/vsource/ModelFieldList.html:47
			if f.PluralName() == plur {
//line views/vsource/ModelFieldList.html:47
				qw422016.N().S(`                  <em>`)
//line views/vsource/ModelFieldList.html:48
				qw422016.E().S(f.PluralName())
//line views/vsource/ModelFieldList.html:48
				qw422016.N().S(`</em>
`)
//line views/vsource/ModelFieldList.html:49
			} else {
//line views/vsource/ModelFieldList.html:49
				qw422016.N().S(`                  `)
//line views/vsource/ModelFieldList.html:50
				qw422016.E().S(f.PluralName())
//line views/vsource/ModelFieldList.html:50
				qw422016.N().S(`
`)
//line views/vsource/ModelFieldList.html:51
			}
//line views/vsource/ModelFieldList.html:51
			qw422016.N().S(`                </label>
                <div class="x">
                  `)
//line views/vsource/ModelFieldList.html:54
			components.StreamFormInput(qw422016, fmt.Sprintf("f.%s.plural", f.Key), f.Key+"-plural", f.PluralName())
//line views/vsource/ModelFieldList.html:54
			qw422016.N().S(`
                </div>
              </div>
            </td>
            <td>`)
//line views/vsource/ModelFieldList.html:58
			fieldview.StreamType(qw422016, f.Type)
//line views/vsource/ModelFieldList.html:58
			qw422016.N().S(`</td>
          </tr>
`)
//line views/vsource/ModelFieldList.html:60
		}
//line views/vsource/ModelFieldList.html:60
		qw422016.N().S(`        </tbody>
      </table>
      <div class="mt">
        <button type="submit">Save All Changes</button>
        <button type="reset">Reset</button>
      </div>
    </div>
`)
//line views/vsource/ModelFieldList.html:68
	}
//line views/vsource/ModelFieldList.html:68
}

//line views/vsource/ModelFieldList.html:68
func WriteModelFieldList(qq422016 qtio422016.Writer, m *model.Model, as *app.State, ps *cutil.PageState) {
//line views/vsource/ModelFieldList.html:68
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vsource/ModelFieldList.html:68
	StreamModelFieldList(qw422016, m, as, ps)
//line views/vsource/ModelFieldList.html:68
	qt422016.ReleaseWriter(qw422016)
//line views/vsource/ModelFieldList.html:68
}

//line views/vsource/ModelFieldList.html:68
func ModelFieldList(m *model.Model, as *app.State, ps *cutil.PageState) string {
//line views/vsource/ModelFieldList.html:68
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vsource/ModelFieldList.html:68
	WriteModelFieldList(qb422016, m, as, ps)
//line views/vsource/ModelFieldList.html:68
	qs422016 := string(qb422016.B)
//line views/vsource/ModelFieldList.html:68
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vsource/ModelFieldList.html:68
	return qs422016
//line views/vsource/ModelFieldList.html:68
}
