// Code generated by qtc from "ModelIndexList.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/vsource/ModelIndexList.html:1
package vsource

//line views/vsource/ModelIndexList.html:1
import (
	"github.com/kyleu/admini/app"
	"github.com/kyleu/admini/app/controller/cutil"
	"github.com/kyleu/admini/app/lib/schema/model"
	"github.com/kyleu/admini/app/util"
	"github.com/kyleu/admini/views/components/fieldview"
)

//line views/vsource/ModelIndexList.html:9
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/vsource/ModelIndexList.html:9
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/vsource/ModelIndexList.html:9
func StreamModelIndexList(qw422016 *qt422016.Writer, m *model.Model, as *app.State, ps *cutil.PageState) {
//line views/vsource/ModelIndexList.html:9
	if len(m.Indexes) > 0 {
//line views/vsource/ModelIndexList.html:9
		qw422016.N().S(`    <div class="card">
      <h3>`)
//line views/vsource/ModelIndexList.html:11
		qw422016.E().S(util.StringPlural(len(m.Indexes), `index`))
//line views/vsource/ModelIndexList.html:11
		qw422016.N().S(`</h3>
      <table>
        <thead>
          <tr>
            <th>Key</th>
            <th>Fields</th>
            <th>Unique</th>
            <th title="Primary Key">PK</th>
          </tr>
        </thead>
        <tbody>
`)
//line views/vsource/ModelIndexList.html:22
		for _, idx := range m.Indexes {
//line views/vsource/ModelIndexList.html:22
			qw422016.N().S(`          <tr>
            <td>`)
//line views/vsource/ModelIndexList.html:24
			fieldview.StreamString(qw422016, idx.Key)
//line views/vsource/ModelIndexList.html:24
			qw422016.N().S(`</td>
            <td>`)
//line views/vsource/ModelIndexList.html:25
			fieldview.StreamArrayString(qw422016, idx.Fields)
//line views/vsource/ModelIndexList.html:25
			qw422016.N().S(`</td>
            <td>`)
//line views/vsource/ModelIndexList.html:26
			fieldview.StreamBoolean(qw422016, idx.Unique)
//line views/vsource/ModelIndexList.html:26
			qw422016.N().S(`</td>
            <td>`)
//line views/vsource/ModelIndexList.html:27
			fieldview.StreamBoolean(qw422016, idx.Primary)
//line views/vsource/ModelIndexList.html:27
			qw422016.N().S(`</td>
          </tr>
`)
//line views/vsource/ModelIndexList.html:29
		}
//line views/vsource/ModelIndexList.html:29
		qw422016.N().S(`        </tbody>
      </table>
    </div>
`)
//line views/vsource/ModelIndexList.html:33
	}
//line views/vsource/ModelIndexList.html:33
}

//line views/vsource/ModelIndexList.html:33
func WriteModelIndexList(qq422016 qtio422016.Writer, m *model.Model, as *app.State, ps *cutil.PageState) {
//line views/vsource/ModelIndexList.html:33
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vsource/ModelIndexList.html:33
	StreamModelIndexList(qw422016, m, as, ps)
//line views/vsource/ModelIndexList.html:33
	qt422016.ReleaseWriter(qw422016)
//line views/vsource/ModelIndexList.html:33
}

//line views/vsource/ModelIndexList.html:33
func ModelIndexList(m *model.Model, as *app.State, ps *cutil.PageState) string {
//line views/vsource/ModelIndexList.html:33
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vsource/ModelIndexList.html:33
	WriteModelIndexList(qb422016, m, as, ps)
//line views/vsource/ModelIndexList.html:33
	qs422016 := string(qb422016.B)
//line views/vsource/ModelIndexList.html:33
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vsource/ModelIndexList.html:33
	return qs422016
//line views/vsource/ModelIndexList.html:33
}
