// Code generated by qtc from "ListTypes.sql". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// --

//line queries/qpostgres/ListTypes.sql:1
package qpostgres

//line queries/qpostgres/ListTypes.sql:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line queries/qpostgres/ListTypes.sql:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line queries/qpostgres/ListTypes.sql:1
func StreamListTypes(qw422016 *qt422016.Writer, schema string) {
//line queries/qpostgres/ListTypes.sql:1
	qw422016.N().S(`
select
  n.nspname as "schema",
  pg_catalog.format_type(t.oid, null) as "name",
  t.typname as "internal",
  case when t.typrelid != 0
         then CAST('tuple' as pg_catalog.text)
       when t.typlen < 0
         then CAST('var' as pg_catalog.text)
       else CAST(t.typlen as pg_catalog.text)
    end as "size",
  pg_catalog.array_to_string(
      ARRAY(
          select e.enumlabel
          from pg_catalog.pg_enum e
          where e.enumtypid = t.oid
          order by e.enumsortorder
        ),
      E'\n'
    ) as "elements",
  pg_catalog.pg_get_userbyid(t.typowner) as "owner",
  pg_catalog.array_to_string(t.typacl, E'\n') as "privileges",
  pg_catalog.obj_description(t.oid, 'pg_type') as "description"
from
  pg_catalog.pg_type t
  left join pg_catalog.pg_namespace n on n.oid = t.typnamespace
where
  (t.typrelid = 0 or (select c.relkind = 'c' from pg_catalog.pg_class c where c.oid = t.typrelid))
  and not EXISTS(select 1 from pg_catalog.pg_type el where el.oid = t.typelem and el.typarray = t.oid)
  and n.nspname <> 'pg_catalog'
  and n.nspname <> 'information_schema'
  and pg_catalog.pg_type_is_visible(t.oid)
  and t.typcategory = 'E'
order by
  1,
  2
;
-- `)
//line queries/qpostgres/ListTypes.sql:38
}

//line queries/qpostgres/ListTypes.sql:38
func WriteListTypes(qq422016 qtio422016.Writer, schema string) {
//line queries/qpostgres/ListTypes.sql:38
	qw422016 := qt422016.AcquireWriter(qq422016)
//line queries/qpostgres/ListTypes.sql:38
	StreamListTypes(qw422016, schema)
//line queries/qpostgres/ListTypes.sql:38
	qt422016.ReleaseWriter(qw422016)
//line queries/qpostgres/ListTypes.sql:38
}

//line queries/qpostgres/ListTypes.sql:38
func ListTypes(schema string) string {
//line queries/qpostgres/ListTypes.sql:38
	qb422016 := qt422016.AcquireByteBuffer()
//line queries/qpostgres/ListTypes.sql:38
	WriteListTypes(qb422016, schema)
//line queries/qpostgres/ListTypes.sql:38
	qs422016 := string(qb422016.B)
//line queries/qpostgres/ListTypes.sql:38
	qt422016.ReleaseByteBuffer(qb422016)
//line queries/qpostgres/ListTypes.sql:38
	return qs422016
//line queries/qpostgres/ListTypes.sql:38
}
