// Code generated by qtc from "ListForeignKeys.sql". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// --

//line queries/qpostgres/ListForeignKeys.sql:1
package qpostgres

//line queries/qpostgres/ListForeignKeys.sql:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line queries/qpostgres/ListForeignKeys.sql:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line queries/qpostgres/ListForeignKeys.sql:1
func StreamListForeignKeys(qw422016 *qt422016.Writer, schema string) {
//line queries/qpostgres/ListForeignKeys.sql:1
	qw422016.N().S(`
select
  c.constraint_name,
  x.ordinal_position as ordinal,
  x.table_schema as schema_name,
  x.table_name,
  x.column_name,
  y.table_schema as foreign_schema_name,
  y.table_name as foreign_table_name,
  y.column_name as foreign_column_name
from
  information_schema.referential_constraints c
    join information_schema.key_column_usage x on x.constraint_name = c.constraint_name
    join information_schema.key_column_usage y on y.ordinal_position = x.position_in_unique_constraint and y.constraint_name = c.unique_constraint_name
`)
//line queries/qpostgres/ListForeignKeys.sql:15
	if schema != "" {
//line queries/qpostgres/ListForeignKeys.sql:15
		qw422016.N().S(`where x.table_schema = '`)
//line queries/qpostgres/ListForeignKeys.sql:15
		qw422016.E().S(schema)
//line queries/qpostgres/ListForeignKeys.sql:15
		qw422016.N().S(`'`)
//line queries/qpostgres/ListForeignKeys.sql:15
	}
//line queries/qpostgres/ListForeignKeys.sql:15
	qw422016.N().S(`
order by
  c.constraint_name,
  x.ordinal_position;
-- `)
//line queries/qpostgres/ListForeignKeys.sql:19
}

//line queries/qpostgres/ListForeignKeys.sql:19
func WriteListForeignKeys(qq422016 qtio422016.Writer, schema string) {
//line queries/qpostgres/ListForeignKeys.sql:19
	qw422016 := qt422016.AcquireWriter(qq422016)
//line queries/qpostgres/ListForeignKeys.sql:19
	StreamListForeignKeys(qw422016, schema)
//line queries/qpostgres/ListForeignKeys.sql:19
	qt422016.ReleaseWriter(qw422016)
//line queries/qpostgres/ListForeignKeys.sql:19
}

//line queries/qpostgres/ListForeignKeys.sql:19
func ListForeignKeys(schema string) string {
//line queries/qpostgres/ListForeignKeys.sql:19
	qb422016 := qt422016.AcquireByteBuffer()
//line queries/qpostgres/ListForeignKeys.sql:19
	WriteListForeignKeys(qb422016, schema)
//line queries/qpostgres/ListForeignKeys.sql:19
	qs422016 := string(qb422016.B)
//line queries/qpostgres/ListForeignKeys.sql:19
	qt422016.ReleaseByteBuffer(qb422016)
//line queries/qpostgres/ListForeignKeys.sql:19
	return qs422016
//line queries/qpostgres/ListForeignKeys.sql:19
}
