// Code generated by qtc from "Any.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/components/fieldedit/Any.html:1
package fieldedit

//line views/components/fieldedit/Any.html:1
import (
	"fmt"
	"github.com/kyleu/admini/app/types"
)

//line views/components/fieldedit/Any.html:6
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/components/fieldedit/Any.html:6
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/components/fieldedit/Any.html:6
func StreamAny(qw422016 *qt422016.Writer, x interface{}, t *types.Wrapped, k string) {
//line views/components/fieldedit/Any.html:7
	switch t.Key() {
//line views/components/fieldedit/Any.html:8
	case "option":
//line views/components/fieldedit/Any.html:9
		StreamOption(qw422016, x, t.T.(*types.Option), k)
//line views/components/fieldedit/Any.html:10
	case "string":
//line views/components/fieldedit/Any.html:11
		StreamString(qw422016, x, k)
//line views/components/fieldedit/Any.html:12
	case "int":
//line views/components/fieldedit/Any.html:13
		StreamInt(qw422016, x, k)
//line views/components/fieldedit/Any.html:14
	case "bool":
//line views/components/fieldedit/Any.html:15
		StreamBoolean(qw422016, x, false, k)
//line views/components/fieldedit/Any.html:16
	default:
//line views/components/fieldedit/Any.html:17
		StreamDefault(qw422016, x, t, k)
//line views/components/fieldedit/Any.html:18
	}
//line views/components/fieldedit/Any.html:19
}

//line views/components/fieldedit/Any.html:19
func WriteAny(qq422016 qtio422016.Writer, x interface{}, t *types.Wrapped, k string) {
//line views/components/fieldedit/Any.html:19
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/components/fieldedit/Any.html:19
	StreamAny(qw422016, x, t, k)
//line views/components/fieldedit/Any.html:19
	qt422016.ReleaseWriter(qw422016)
//line views/components/fieldedit/Any.html:19
}

//line views/components/fieldedit/Any.html:19
func Any(x interface{}, t *types.Wrapped, k string) string {
//line views/components/fieldedit/Any.html:19
	qb422016 := qt422016.AcquireByteBuffer()
//line views/components/fieldedit/Any.html:19
	WriteAny(qb422016, x, t, k)
//line views/components/fieldedit/Any.html:19
	qs422016 := string(qb422016.B)
//line views/components/fieldedit/Any.html:19
	qt422016.ReleaseByteBuffer(qb422016)
//line views/components/fieldedit/Any.html:19
	return qs422016
//line views/components/fieldedit/Any.html:19
}

//line views/components/fieldedit/Any.html:21
func StreamDefault(qw422016 *qt422016.Writer, x interface{}, t types.Type, k string) {
//line views/components/fieldedit/Any.html:23
	msg := fmt.Sprintf("unhandled type: %s (%T)", t.String(), x)
	if x == nil {
		x = "∅"
	}

//line views/components/fieldedit/Any.html:27
	qw422016.N().S(`<input title="`)
//line views/components/fieldedit/Any.html:28
	qw422016.E().S(msg)
//line views/components/fieldedit/Any.html:28
	qw422016.N().S(`" value="`)
//line views/components/fieldedit/Any.html:28
	qw422016.E().V(x)
//line views/components/fieldedit/Any.html:28
	qw422016.N().S(`" name="`)
//line views/components/fieldedit/Any.html:28
	qw422016.E().S(k)
//line views/components/fieldedit/Any.html:28
	qw422016.N().S(`" />`)
//line views/components/fieldedit/Any.html:29
}

//line views/components/fieldedit/Any.html:29
func WriteDefault(qq422016 qtio422016.Writer, x interface{}, t types.Type, k string) {
//line views/components/fieldedit/Any.html:29
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/components/fieldedit/Any.html:29
	StreamDefault(qw422016, x, t, k)
//line views/components/fieldedit/Any.html:29
	qt422016.ReleaseWriter(qw422016)
//line views/components/fieldedit/Any.html:29
}

//line views/components/fieldedit/Any.html:29
func Default(x interface{}, t types.Type, k string) string {
//line views/components/fieldedit/Any.html:29
	qb422016 := qt422016.AcquireByteBuffer()
//line views/components/fieldedit/Any.html:29
	WriteDefault(qb422016, x, t, k)
//line views/components/fieldedit/Any.html:29
	qs422016 := string(qb422016.B)
//line views/components/fieldedit/Any.html:29
	qt422016.ReleaseByteBuffer(qb422016)
//line views/components/fieldedit/Any.html:29
	return qs422016
//line views/components/fieldedit/Any.html:29
}
