// Code generated by qtc from "Int.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/components/fieldedit/Int.html:1
package fieldedit

//line views/components/fieldedit/Int.html:1
import (
	"github.com/kyleu/admini/views/components"
)

//line views/components/fieldedit/Int.html:5
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/components/fieldedit/Int.html:5
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/components/fieldedit/Int.html:5
func StreamInt(qw422016 *qt422016.Writer, x interface{}, k string) {
//line views/components/fieldedit/Int.html:6
	components.StreamFormInputNumber(qw422016, k, "", x)
//line views/components/fieldedit/Int.html:7
}

//line views/components/fieldedit/Int.html:7
func WriteInt(qq422016 qtio422016.Writer, x interface{}, k string) {
//line views/components/fieldedit/Int.html:7
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/components/fieldedit/Int.html:7
	StreamInt(qw422016, x, k)
//line views/components/fieldedit/Int.html:7
	qt422016.ReleaseWriter(qw422016)
//line views/components/fieldedit/Int.html:7
}

//line views/components/fieldedit/Int.html:7
func Int(x interface{}, k string) string {
//line views/components/fieldedit/Int.html:7
	qb422016 := qt422016.AcquireByteBuffer()
//line views/components/fieldedit/Int.html:7
	WriteInt(qb422016, x, k)
//line views/components/fieldedit/Int.html:7
	qs422016 := string(qb422016.B)
//line views/components/fieldedit/Int.html:7
	qt422016.ReleaseByteBuffer(qb422016)
//line views/components/fieldedit/Int.html:7
	return qs422016
//line views/components/fieldedit/Int.html:7
}
