// Code generated by qtc from "Option.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/components/fieldedit/Option.html:1
package fieldedit

//line views/components/fieldedit/Option.html:1
import (
	"github.com/kyleu/admini/app/types"
)

//line views/components/fieldedit/Option.html:5
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/components/fieldedit/Option.html:5
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/components/fieldedit/Option.html:5
func StreamOption(qw422016 *qt422016.Writer, x interface{}, t *types.Option, k string) {
//line views/components/fieldedit/Option.html:6
	switch t.V.Key() {
//line views/components/fieldedit/Option.html:7
	case "bool":
//line views/components/fieldedit/Option.html:8
		StreamBoolean(qw422016, x, true, k)
//line views/components/fieldedit/Option.html:9
	default:
//line views/components/fieldedit/Option.html:9
		qw422016.N().S(`<div class="two-pane"><div class="l">`)
//line views/components/fieldedit/Option.html:11
		StreamAny(qw422016, x, t.V, k)
//line views/components/fieldedit/Option.html:11
		qw422016.N().S(`</div><div class="r"><button title="click to set field to null" type="button" onclick="admini.setSiblingToNull(this);">∅</button></div></div>`)
//line views/components/fieldedit/Option.html:14
	}
//line views/components/fieldedit/Option.html:15
}

//line views/components/fieldedit/Option.html:15
func WriteOption(qq422016 qtio422016.Writer, x interface{}, t *types.Option, k string) {
//line views/components/fieldedit/Option.html:15
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/components/fieldedit/Option.html:15
	StreamOption(qw422016, x, t, k)
//line views/components/fieldedit/Option.html:15
	qt422016.ReleaseWriter(qw422016)
//line views/components/fieldedit/Option.html:15
}

//line views/components/fieldedit/Option.html:15
func Option(x interface{}, t *types.Option, k string) string {
//line views/components/fieldedit/Option.html:15
	qb422016 := qt422016.AcquireByteBuffer()
//line views/components/fieldedit/Option.html:15
	WriteOption(qb422016, x, t, k)
//line views/components/fieldedit/Option.html:15
	qs422016 := string(qb422016.B)
//line views/components/fieldedit/Option.html:15
	qt422016.ReleaseByteBuffer(qb422016)
//line views/components/fieldedit/Option.html:15
	return qs422016
//line views/components/fieldedit/Option.html:15
}
