// Code generated by qtc from "String.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/components/fieldedit/String.html:1
package fieldedit

//line views/components/fieldedit/String.html:1
import (
	"fmt"
	"github.com/kyleu/admini/views/components"
)

//line views/components/fieldedit/String.html:6
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/components/fieldedit/String.html:6
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/components/fieldedit/String.html:6
func StreamString(qw422016 *qt422016.Writer, x interface{}, k string) {
//line views/components/fieldedit/String.html:7
	components.StreamFormInput(qw422016, k, "", fmt.Sprintf("%v", x))
//line views/components/fieldedit/String.html:8
}

//line views/components/fieldedit/String.html:8
func WriteString(qq422016 qtio422016.Writer, x interface{}, k string) {
//line views/components/fieldedit/String.html:8
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/components/fieldedit/String.html:8
	StreamString(qw422016, x, k)
//line views/components/fieldedit/String.html:8
	qt422016.ReleaseWriter(qw422016)
//line views/components/fieldedit/String.html:8
}

//line views/components/fieldedit/String.html:8
func String(x interface{}, k string) string {
//line views/components/fieldedit/String.html:8
	qb422016 := qt422016.AcquireByteBuffer()
//line views/components/fieldedit/String.html:8
	WriteString(qb422016, x, k)
//line views/components/fieldedit/String.html:8
	qs422016 := string(qb422016.B)
//line views/components/fieldedit/String.html:8
	qt422016.ReleaseByteBuffer(qb422016)
//line views/components/fieldedit/String.html:8
	return qs422016
//line views/components/fieldedit/String.html:8
}
