// Code generated by qtc from "ListTables.sql". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// --

//line queries/qsqlite/ListTables.sql:1
package qsqlite

//line queries/qsqlite/ListTables.sql:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line queries/qsqlite/ListTables.sql:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line queries/qsqlite/ListTables.sql:1
func StreamListTables(qw422016 *qt422016.Writer, schema string) {
//line queries/qsqlite/ListTables.sql:1
	qw422016.N().S(`
select
  m.type as "t",
  m.name as "n"
from
  sqlite_master m
where
  m.type in ('table', 'view')
order by
  n
;
-- `)
//line queries/qsqlite/ListTables.sql:12
}

//line queries/qsqlite/ListTables.sql:12
func WriteListTables(qq422016 qtio422016.Writer, schema string) {
//line queries/qsqlite/ListTables.sql:12
	qw422016 := qt422016.AcquireWriter(qq422016)
//line queries/qsqlite/ListTables.sql:12
	StreamListTables(qw422016, schema)
//line queries/qsqlite/ListTables.sql:12
	qt422016.ReleaseWriter(qw422016)
//line queries/qsqlite/ListTables.sql:12
}

//line queries/qsqlite/ListTables.sql:12
func ListTables(schema string) string {
//line queries/qsqlite/ListTables.sql:12
	qb422016 := qt422016.AcquireByteBuffer()
//line queries/qsqlite/ListTables.sql:12
	WriteListTables(qb422016, schema)
//line queries/qsqlite/ListTables.sql:12
	qs422016 := string(qb422016.B)
//line queries/qsqlite/ListTables.sql:12
	qt422016.ReleaseByteBuffer(qb422016)
//line queries/qsqlite/ListTables.sql:12
	return qs422016
//line queries/qsqlite/ListTables.sql:12
}
