// Code generated by qtc from "ListForeignKeys.sql". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// --

//line queries/qsqlite/ListForeignKeys.sql:1
package qsqlite

//line queries/qsqlite/ListForeignKeys.sql:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line queries/qsqlite/ListForeignKeys.sql:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line queries/qsqlite/ListForeignKeys.sql:1
func StreamListForeignKeys(qw422016 *qt422016.Writer, schema string) {
//line queries/qsqlite/ListForeignKeys.sql:1
	qw422016.N().S(`
select
  p.seq as "idx",
  m.tbl_name as "src",
  p."from" as "src_col",
  p."table" as "tgt",
  p."to" as "tgt_col"
from
  sqlite_master m
  left outer join pragma_foreign_key_list(m.name) p on m.name <> p.[table]
where
  m.type in ('table', 'view')
  and "src_col" is not null
;
-- `)
//line queries/qsqlite/ListForeignKeys.sql:15
}

//line queries/qsqlite/ListForeignKeys.sql:15
func WriteListForeignKeys(qq422016 qtio422016.Writer, schema string) {
//line queries/qsqlite/ListForeignKeys.sql:15
	qw422016 := qt422016.AcquireWriter(qq422016)
//line queries/qsqlite/ListForeignKeys.sql:15
	StreamListForeignKeys(qw422016, schema)
//line queries/qsqlite/ListForeignKeys.sql:15
	qt422016.ReleaseWriter(qw422016)
//line queries/qsqlite/ListForeignKeys.sql:15
}

//line queries/qsqlite/ListForeignKeys.sql:15
func ListForeignKeys(schema string) string {
//line queries/qsqlite/ListForeignKeys.sql:15
	qb422016 := qt422016.AcquireByteBuffer()
//line queries/qsqlite/ListForeignKeys.sql:15
	WriteListForeignKeys(qb422016, schema)
//line queries/qsqlite/ListForeignKeys.sql:15
	qs422016 := string(qb422016.B)
//line queries/qsqlite/ListForeignKeys.sql:15
	qt422016.ReleaseByteBuffer(qb422016)
//line queries/qsqlite/ListForeignKeys.sql:15
	return qs422016
//line queries/qsqlite/ListForeignKeys.sql:15
}
