// Code generated by qtc from "ListIndexes.sql". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// --

//line queries/qsqlite/ListIndexes.sql:1
package qsqlite

//line queries/qsqlite/ListIndexes.sql:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line queries/qsqlite/ListIndexes.sql:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line queries/qsqlite/ListIndexes.sql:1
func StreamListIndexes(qw422016 *qt422016.Writer, schema string) {
//line queries/qsqlite/ListIndexes.sql:1
	qw422016.N().S(`
select
  m.name as "n",
  m.tbl_name as "xn",
  p.name as "cn",
  p.seqno as "ci"
from
  sqlite_master m
  left outer join pragma_index_info(m.name) p on m.name <> p.name
where
  m.type='index'
order by
  m.name, p.seqno
;
-- `)
//line queries/qsqlite/ListIndexes.sql:15
}

//line queries/qsqlite/ListIndexes.sql:15
func WriteListIndexes(qq422016 qtio422016.Writer, schema string) {
//line queries/qsqlite/ListIndexes.sql:15
	qw422016 := qt422016.AcquireWriter(qq422016)
//line queries/qsqlite/ListIndexes.sql:15
	StreamListIndexes(qw422016, schema)
//line queries/qsqlite/ListIndexes.sql:15
	qt422016.ReleaseWriter(qw422016)
//line queries/qsqlite/ListIndexes.sql:15
}

//line queries/qsqlite/ListIndexes.sql:15
func ListIndexes(schema string) string {
//line queries/qsqlite/ListIndexes.sql:15
	qb422016 := qt422016.AcquireByteBuffer()
//line queries/qsqlite/ListIndexes.sql:15
	WriteListIndexes(qb422016, schema)
//line queries/qsqlite/ListIndexes.sql:15
	qs422016 := string(qb422016.B)
//line queries/qsqlite/ListIndexes.sql:15
	qt422016.ReleaseByteBuffer(qb422016)
//line queries/qsqlite/ListIndexes.sql:15
	return qs422016
//line queries/qsqlite/ListIndexes.sql:15
}
