// Code generated by qtc from "Detail.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/vexport/Detail.html:1
package vexport

//line views/vexport/Detail.html:1
import (
	"github.com/kyleu/admini/app"
	"github.com/kyleu/admini/app/controller/cutil"
	"github.com/kyleu/admini/app/export"
	"github.com/kyleu/admini/views/components/fieldview"
	"github.com/kyleu/admini/views/layout"
)

//line views/vexport/Detail.html:9
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/vexport/Detail.html:9
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/vexport/Detail.html:9
type Detail struct {
	layout.Basic
	Format  *export.Format
	Results []*export.Result
}

//line views/vexport/Detail.html:15
func (p *Detail) StreamBody(qw422016 *qt422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vexport/Detail.html:15
	qw422016.N().S(`
  <div class="card">
    <h3>`)
//line views/vexport/Detail.html:17
	qw422016.E().S(ps.Title)
//line views/vexport/Detail.html:17
	qw422016.N().S(`</h3>
    <em>`)
//line views/vexport/Detail.html:18
	qw422016.E().S(p.Format.Language)
//line views/vexport/Detail.html:18
	qw422016.N().S(` - `)
//line views/vexport/Detail.html:18
	qw422016.E().S(p.Format.Flavor)
//line views/vexport/Detail.html:18
	qw422016.N().S(`</em>
  </div>
`)
//line views/vexport/Detail.html:20
	for _, r := range p.Results {
//line views/vexport/Detail.html:20
		qw422016.N().S(`  <div class="card">
    <h3>`)
//line views/vexport/Detail.html:22
		qw422016.E().S(r.Key)
//line views/vexport/Detail.html:22
		qw422016.N().S(`</h3>
    `)
//line views/vexport/Detail.html:23
		fieldview.StreamCode(qw422016, r.Out.RenderString(), p.Format.Language)
//line views/vexport/Detail.html:23
		qw422016.N().S(`
  </div>
`)
//line views/vexport/Detail.html:25
	}
//line views/vexport/Detail.html:26
}

//line views/vexport/Detail.html:26
func (p *Detail) WriteBody(qq422016 qtio422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vexport/Detail.html:26
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vexport/Detail.html:26
	p.StreamBody(qw422016, as, ps)
//line views/vexport/Detail.html:26
	qt422016.ReleaseWriter(qw422016)
//line views/vexport/Detail.html:26
}

//line views/vexport/Detail.html:26
func (p *Detail) Body(as *app.State, ps *cutil.PageState) string {
//line views/vexport/Detail.html:26
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vexport/Detail.html:26
	p.WriteBody(qb422016, as, ps)
//line views/vexport/Detail.html:26
	qs422016 := string(qb422016.B)
//line views/vexport/Detail.html:26
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vexport/Detail.html:26
	return qs422016
//line views/vexport/Detail.html:26
}
