// Code generated by qtc from "Settings.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// <!-- Content managed by Project Forge, see [projectforge.md] for details. -->

//line views/vadmin/Settings.html:2
package vadmin

//line views/vadmin/Settings.html:2
import (
	"github.com/kyleu/admini/app"
	"github.com/kyleu/admini/app/controller/cutil"
	"github.com/kyleu/admini/app/lib/user"
	"github.com/kyleu/admini/app/util"
	"github.com/kyleu/admini/views/components"
	"github.com/kyleu/admini/views/layout"
	"github.com/kyleu/admini/views/vauth"
	"runtime"
)

//line views/vadmin/Settings.html:13
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/vadmin/Settings.html:13
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/vadmin/Settings.html:13
type Settings struct {
	layout.Basic
	Perms user.Permissions
	Mem   *runtime.MemStats
}

//line views/vadmin/Settings.html:19
func (p *Settings) StreamBody(qw422016 *qt422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vadmin/Settings.html:19
	qw422016.N().S(`
  <div class="card">
`)
//line views/vadmin/Settings.html:21
	if util.AppSource != "" {
//line views/vadmin/Settings.html:21
		qw422016.N().S(`    <div class="right"><a href="`)
//line views/vadmin/Settings.html:22
		qw422016.E().S(util.AppSource)
//line views/vadmin/Settings.html:22
		qw422016.N().S(`"><button>Github</button></a></div>
`)
//line views/vadmin/Settings.html:23
	}
//line views/vadmin/Settings.html:23
	qw422016.N().S(`    <h3 title="github:`)
//line views/vadmin/Settings.html:24
	qw422016.E().S(as.BuildInfo.Commit)
//line views/vadmin/Settings.html:24
	qw422016.N().S(`">`)
//line views/vadmin/Settings.html:24
	qw422016.E().S(util.AppName)
//line views/vadmin/Settings.html:24
	qw422016.N().S(` `)
//line views/vadmin/Settings.html:24
	qw422016.E().S(as.BuildInfo.String())
//line views/vadmin/Settings.html:24
	qw422016.N().S(`</h3>
`)
//line views/vadmin/Settings.html:25
	if util.AppLegal != "" {
//line views/vadmin/Settings.html:25
		qw422016.N().S(`    <div>`)
//line views/vadmin/Settings.html:26
		qw422016.N().S(util.AppLegal)
//line views/vadmin/Settings.html:26
		qw422016.N().S(`</div>
`)
//line views/vadmin/Settings.html:27
	}
//line views/vadmin/Settings.html:28
	if util.AppURL != "" {
//line views/vadmin/Settings.html:28
		qw422016.N().S(`    <p><a href="`)
//line views/vadmin/Settings.html:29
		qw422016.N().S(util.AppURL)
//line views/vadmin/Settings.html:29
		qw422016.N().S(`">`)
//line views/vadmin/Settings.html:29
		qw422016.N().S(util.AppURL)
//line views/vadmin/Settings.html:29
		qw422016.N().S(`</a></p>
`)
//line views/vadmin/Settings.html:30
	}
//line views/vadmin/Settings.html:30
	qw422016.N().S(`  </div>

  <div class="card">
    <div class="right"><a href="#modal-mem"><button type="button">Memory Usage</button></a></div>
    `)
//line views/vadmin/Settings.html:35
	components.StreamJSONModal(qw422016, "mem", "Memory Usage", p.Mem, 1)
//line views/vadmin/Settings.html:35
	qw422016.N().S(`
    <h3>Admin Functions</h3>
    <ul class="mt">
      <li><a href="/admin/modules">View Go modules</a></li>
      <li><a href="/admin/session">Parse and display session</a></li>
      <li><a href="/admin/request">Debug HTTP request</a></li>
      <li><a href="/admin/cpu/start">Start CPU profile</a></li>
      <li><a href="/admin/cpu/stop">Stop CPU profile</a></li>
      <li><a href="/admin/heap">Write memory dump</a></li>
      <li><a href="/admin/gc">Collect garbage</a></li>
    </ul>
  </div>

  <div class="card">
    <h3>Themes</h3>
    <ul class="mt">
      <li><a href="/theme">Edit Themes</a></li>
    </ul>
  </div>

  `)
//line views/vadmin/Settings.html:55
	vauth.StreamAuthentication(qw422016, as)
//line views/vadmin/Settings.html:55
	qw422016.N().S(`

  `)
//line views/vadmin/Settings.html:57
	vauth.StreamPermissions(qw422016, p.Perms, as)
//line views/vadmin/Settings.html:57
	qw422016.N().S(`
`)
//line views/vadmin/Settings.html:58
}

//line views/vadmin/Settings.html:58
func (p *Settings) WriteBody(qq422016 qtio422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vadmin/Settings.html:58
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vadmin/Settings.html:58
	p.StreamBody(qw422016, as, ps)
//line views/vadmin/Settings.html:58
	qt422016.ReleaseWriter(qw422016)
//line views/vadmin/Settings.html:58
}

//line views/vadmin/Settings.html:58
func (p *Settings) Body(as *app.State, ps *cutil.PageState) string {
//line views/vadmin/Settings.html:58
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vadmin/Settings.html:58
	p.WriteBody(qb422016, as, ps)
//line views/vadmin/Settings.html:58
	qs422016 := string(qb422016.B)
//line views/vadmin/Settings.html:58
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vadmin/Settings.html:58
	return qs422016
//line views/vadmin/Settings.html:58
}
