// Code generated by projectforge.dev using code from the [types] module, which is under license [CC0]
package types

import (
	"fmt"
)

type Type interface {
	Key() string
	fmt.Stringer
	Sortable() bool
	From(v interface{}) interface{}
	Default(key string) interface{}
}
