// Code generated by projectforge.dev using code from the [types] module, which is under license [CC0]
package types

import "fmt"

const emptyList = "[]"

func invalidInput(key string, v interface{}) string {
	return fmt.Sprintf("unable to parse [%s] from [%v] (%T)", key, v, v)
}
